using System;
using Clio.Common;
using Clio.Package;
using Clio.Requests;
using Clio.Tests.Command;
using Clio.WebApplication;
using FluentAssertions;
using NSubstitute;
using NUnit.Framework;

namespace Clio.Tests.Package;

/// <summary>
/// GH-1299: binding coverage for the classification the installers apply to the answer of
/// <c>PackageInstallerService.svc/InstallPackage</c>. <see cref="InstallLogAnalyzerTests"/> pins the pure
/// classifier; these tests prove that <see cref="BasePackageInstaller"/> actually asks it, and that the
/// dedicated invalid-archive exit code still wins over the downgrade.
/// </summary>
// [NonParallelizable] because Setup/TearDown mutate the process-global GlobalContext.FailOnError, which
// BasePackageInstaller.CheckLogsOnSuccessMessage reads live during Install() - and the assembly runs fixtures
// in parallel (TestAssemblySetup declares [assembly: Parallelizable(ParallelScope.Fixtures)]). Saving and
// restoring the flag around each test is not enough: ApplicationInstallerTests writes true without restoring,
// so a fixture running CONCURRENTLY can flip the value between this fixture's Setup and its Install() call,
// in either direction.
[TestFixture]
[Category("Unit")]
[Property("Module", "Package")]
[NonParallelizable]
internal sealed class InstallerFailureClassificationTests : BaseClioModuleTests {

	private const string GenericFailureResponse =
		"{\"success\":false,\"errorInfo\":{\"errorCode\":\"Exception\",\"message\":\"Packages installation failed\"}}";

	/// <summary>
	/// What the log endpoint answers BEFORE the installation starts. The platform rewrites the install log
	/// when the archive is uploaded, so the pre-install read already carries the upload and backup lines and
	/// the post-install read extends it - that is what makes the length subtraction in
	/// <c>BasePackageInstaller.GetLogDiff</c> a real delta.
	/// </summary>
	private const string BaselineLog =
		"Loading file: UsrIssue1299.gz 100%\r\n"
		+ "Configuration backup started.\r\n"
		+ "Configuration backup successfully created\r\n";

	private const string LocallyModifiedLog =
		"Start package installation\r\n"
		+ "Unable to install Schema \"UsrI1299Svc\" into package \"UsrIssue1299\", because the element has been"
		+ " modified locally. Resolve the conflict and mark the element as unchanged.\r\n"
		+ "Package installation finished\r\n";

	/// <summary>
	/// The measured shape of a mixed run: a schema skipped as modified locally AND a package that failed to
	/// compile, both reaching the platform's completion marker (Creatio 10.1.725, GH-1299).
	/// </summary>
	private const string LocallyModifiedAndCompilationFailedLog =
		"Start package installation\r\n"
		+ "Unable to install Schema \"UsrI1299Svc\" into package \"UsrIssue1299\", because the element has been"
		+ " modified locally. Resolve the conflict and mark the element as unchanged.\r\n"
		+ "Errors and (or) warnings occurred while compiling configuration dll\r\n"
		+ "Autogenerated\\Src\\UsrI1299BadSvc.UsrI1299B.cs(1,79) error CS1519: Invalid token '!=' in a member"
		+ " declaration\r\n"
		+ "Package installation finished\r\n";

	/// <summary>
	/// What the log endpoint sometimes answers instead of the log: an HTML error page that reaches clio as
	/// log content rather than as a failure. Observed repeatedly on the stand the fix was measured on.
	/// </summary>
	private const string HtmlErrorPageLog =
		"<html><body><H1>500 - Internal Server Error</H1></body></html>\r\n";

	private bool _originalFailOnError;
	private ILogger _logger;
	private IApplicationLogProvider _applicationLogProvider;
	private IOwnedApplicationClient _applicationClient;
	private IApplicationClientFactory _applicationClientFactory;

	public override void Setup() {
		base.Setup();
		_originalFailOnError = GlobalContext.FailOnError;
		GlobalContext.FailOnError = false;
		_logger = Substitute.For<ILogger>();
		_applicationLogProvider = Substitute.For<IApplicationLogProvider>();
		_applicationClient = Substitute.For<IOwnedApplicationClient>();
		_applicationClientFactory = Substitute.For<IApplicationClientFactory>();
		_applicationClientFactory.CreateClient(Arg.Any<EnvironmentSettings>()).Returns(_applicationClient);
	}

	public override void TearDown() {
		GlobalContext.FailOnError = _originalFailOnError;
		_applicationClient?.Dispose();
		base.TearDown();
	}

	/// <summary>
	/// Arranges the service answer and the log reads for a healthy log window: the pre-install read returns
	/// the baseline, every later read returns the baseline extended by the installation output.
	/// </summary>
	private void ArrangeServer(string response, string installLog) {
		string completeLog = BaselineLog + installLog;
		ArrangeServer(response, BaselineLog, completeLog);
	}

	/// <summary>
	/// Arranges the service answer and the log reads explicitly, so a test can reproduce a log window that
	/// is not this run's delta.
	/// </summary>
	private void ArrangeServer(string response, string initialLog, string completeLog) {
		_applicationClient.ExecutePostRequest(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<int>())
			.Returns(response);
		_applicationLogProvider.GetInstallationLog(Arg.Any<EnvironmentSettings>())
			.Returns(initialLog, completeLog, completeLog, completeLog);
	}

	private PackageInstaller CreatePackageInstaller(EnvironmentSettings environmentSettings) =>
		CreateInstaller(environmentSettings,
			(logProvider, settings, clientFactory, application, archiver, scriptExecutor, urlBuilder, fileSystem,
					logger, lockManager) =>
				new PackageInstaller(logProvider, settings, clientFactory, application, archiver, scriptExecutor,
					urlBuilder, fileSystem, logger, lockManager));

	private TInstaller CreateInstaller<TInstaller>(EnvironmentSettings environmentSettings,
		Func<IApplicationLogProvider, EnvironmentSettings, IApplicationClientFactory, IApplication,
			IPackageArchiver, ISqlScriptExecutor, IServiceUrlBuilder, IFileSystem, ILogger, IPackageLockManager,
			TInstaller> factory) {
		IServiceUrlBuilder serviceUrlBuilder = Substitute.For<IServiceUrlBuilder>();
		serviceUrlBuilder.Build(Arg.Any<string>(), Arg.Any<EnvironmentSettings>())
			.Returns(callInfo => callInfo.ArgAt<string>(0));
		return factory(_applicationLogProvider, environmentSettings, _applicationClientFactory,
			Substitute.For<IApplication>(), Substitute.For<IPackageArchiver>(),
			Substitute.For<ISqlScriptExecutor>(), serviceUrlBuilder, new FileSystem(FileSystem), _logger,
			Substitute.For<IPackageLockManager>());
	}

	private string AddPackageArchive(string fileName) {
		string packagePath = $"T:\\{fileName}";
		FileSystem.AddFile(packagePath, new System.IO.Abstractions.TestingHelpers.MockFileData(new byte[0]));
		return packagePath;
	}

	[Test]
	[Description("GH-1299: the installer reports success when the service answered with the generic failure message but the run finished and only skipped a locally modified schema.")]
	public void Install_ShouldReturnTrue_WhenTheOnlyReportedProblemWasALocallyModifiedSchema() {
		// Arrange
		EnvironmentSettings environmentSettings = new();
		string packagePath = AddPackageArchive("UsrIssue1299.gz");
		ArrangeServer(GenericFailureResponse, LocallyModifiedLog);
		PackageInstaller installer = CreatePackageInstaller(environmentSettings);

		// Act
		bool result = installer.Install(packagePath, environmentSettings);

		// Assert
		result.Should().BeTrue(
			because: "the package was installed and a schema skipped as modified locally is a warning (GH-1299)");
		_logger.Received().WriteWarning(Arg.Is<string>(value => value.Contains("UsrI1299Svc")));
		_logger.DidNotReceive().WriteError(Arg.Any<string>());
	}

	[Test]
	[Description("GH-1299: a service failure that names a concrete reason stays a failure and the reason reaches the operator.")]
	public void Install_ShouldReturnFalseAndNameTheReason_WhenTheServiceReportedASpecificFailure() {
		// Arrange
		EnvironmentSettings environmentSettings = new();
		string packagePath = AddPackageArchive("UsrIssue1299.gz");
		ArrangeServer(
			"{\"success\":false,\"errorInfo\":{\"errorCode\":\"Exception\",\"message\":\"Cannot compile configuration\"}}",
			LocallyModifiedLog);
		PackageInstaller installer = CreatePackageInstaller(environmentSettings);

		// Act
		bool result = installer.Install(packagePath, environmentSettings);

		// Assert
		result.Should().BeFalse(
			because: "a named reason is a real failure that a locally-modified skip does not explain away");
		_logger.Received().WriteError(Arg.Is<string>(value => value.Contains("Cannot compile configuration")));
	}

	// Covers the throw at the top of InstallPackageOnServerWithLogListener only. It does NOT reach the
	// IsInvalidGZipArchiveFailure guard inside TryDowngradeReportedFailure: ApplicationInstaller overrides
	// ThrowInvalidGZipArchiveInstallException to true, so the throw fires first, and the message-less
	// response would be rejected by IsGenericInstallationFailure anyway. That guard is covered by
	// Install_ShouldReturnFalse_WhenTheGenericFailureLogNamesAnInvalidArchive (GH-1299).
	[Test]
	[Description("GH-1299: the dedicated invalid-archive exception still wins when the same run also skipped a locally modified schema.")]
	public void Install_ShouldStillThrowInvalidGZipArchive_WhenTheRunAlsoSkippedALocallyModifiedSchema() {
		// Arrange
		EnvironmentSettings environmentSettings = new();
		string packagePath = AddPackageArchive("UsrIssue1299App.gz");
		ArrangeServer("{\"success\":false}",
			LocallyModifiedLog
			+ "Terrasoft.Common.InvalidGZipArchiveException: Unable to open \"UsrIssue1299App.gz\"."
			+ " The file is invalid or corrupted.\r\n");
		ApplicationInstaller installer = CreateInstaller(environmentSettings,
			(logProvider, settings, clientFactory, application, archiver, scriptExecutor, urlBuilder, fileSystem,
					logger, lockManager) =>
				new ApplicationInstaller(logProvider, settings, clientFactory, application, archiver, scriptExecutor,
					urlBuilder, fileSystem, logger, lockManager));

		// Act
		Action act = () => installer.Install(packagePath, environmentSettings);

		// Assert
		act.Should().Throw<InvalidGZipArchiveInstallException>(
			because: "install-application maps an invalid archive to its own exit code, which the locally-modified downgrade must never swallow");
	}

	[Test]
	[Description("GH-1299: a run that also failed to compile keeps its non-zero outcome, even though it skipped a locally modified schema and reached the completion marker.")]
	public void Install_ShouldReturnFalse_WhenTheRunAlsoFailedToCompile() {
		// Arrange
		EnvironmentSettings environmentSettings = new();
		string packagePath = AddPackageArchive("mixed.zip");
		ArrangeServer(GenericFailureResponse, LocallyModifiedAndCompilationFailedLog);
		PackageInstaller installer = CreatePackageInstaller(environmentSettings);

		// Act
		bool result = installer.Install(packagePath, environmentSettings);

		// Assert
		result.Should().BeFalse(
			because: "the configuration no longer compiles, which a schema skipped as modified locally does not explain (GH-1299, measured on Creatio 10.1.725)");
		_logger.Received().WriteError(Arg.Any<string>());
	}

	[TestCase("", TestName = "Install_ShouldReturnFalse_WhenThePreInstallLogReadCameBackEmpty")]
	[TestCase(HtmlErrorPageLog, TestName = "Install_ShouldReturnFalse_WhenThePreInstallLogReadCameBackAsAnErrorPage")]
	[Description("GH-1299: the downgrade is refused when the pre-install log read did not return the log, because GetLogDiff then hands the whole shared history to the gate instead of this run's delta.")]
	public void Install_ShouldReturnFalse_WhenTheLogWindowIsNotThisRunsDelta(string initialLog) {
		// Arrange - the empty case is what ApplicationLogProvider.GetInstallationLog returns for ANY failed
		// request, because it swallows the exception; the error-page case is what the endpoint answered with
		// directly on the stand.
		EnvironmentSettings environmentSettings = new();
		string packagePath = AddPackageArchive("UsrIssue1299.gz");
		ArrangeServer(GenericFailureResponse, initialLog, BaselineLog + LocallyModifiedLog);
		PackageInstaller installer = CreatePackageInstaller(environmentSettings);

		// Act
		bool result = installer.Install(packagePath, environmentSettings);

		// Assert
		result.Should().BeFalse(
			because: "the pre-install read did not return the log, so the completion marker and the skip line the gate reads could have been written by any earlier installation on this shared environment rather than by this run");
		_logger.Received().WriteWarning(
			Arg.Is<string>(value => value.Contains("could not be attributed to this run")));
	}

	[Test]
	[Description("GH-1299: an invalid archive reported only through the log keeps the run a failure on the push-pkg path, where no dedicated exception is thrown.")]
	public void Install_ShouldReturnFalse_WhenTheGenericFailureLogNamesAnInvalidArchive() {
		// Arrange
		EnvironmentSettings environmentSettings = new();
		string packagePath = AddPackageArchive("UsrIssue1299Corrupt.gz");
		ArrangeServer(GenericFailureResponse,
			"Start package installation\r\n"
			+ "Unable to install Schema \"UsrI1299Svc\" into package \"UsrIssue1299\", because the element has"
			+ " been modified locally.\r\n"
			+ "Terrasoft.Common.InvalidGZipArchiveException: Unable to open \"UsrIssue1299Corrupt.gz\"."
			+ " The file is invalid or corrupted.\r\n"
			+ "Package installation finished\r\n");
		PackageInstaller installer = CreatePackageInstaller(environmentSettings);

		// Act
		bool result = installer.Install(packagePath, environmentSettings);

		// Assert
		result.Should().BeFalse(
			because: "PackageInstaller does not throw the dedicated exception, so the invalid-archive guard inside the downgrade is the only thing keeping this run a failure");
	}

}
