<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Clio10.SupervisorComposition.Backend</AssemblyName>
    <RootNamespace>Clio10.SupervisorComposition.Backend</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
