stages:
  - deploy
    
deploy:
  stage: deploy
  dependencies: []
  tags:
    - clio
  only:
    - master
  cache:
  script:
    - clio pushw -l $STAGING_LOGIN -p $STAGING_PWD -u $STAGING_URL
    - clio restart -l $STAGING_LOGIN -p $STAGING_PWD -u $STAGING_URL