using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Clio.Command.AddonSchemaDesigner;
using Clio.Command.BusinessRules;
using FluentAssertions;
using NSubstitute;
using NUnit.Framework;

namespace Clio.Tests.Command;

[TestFixture]
[Property("Module", "Command")]
public sealed class BusinessRuleAddonServiceTests {

	private const string RuleAUId = "11111111-1111-1111-1111-111111111111";
	private const string ChildAUId = "22222222-2222-2222-2222-222222222222";
	private const string RuleBUId = "33333333-3333-3333-3333-333333333333";

	private IAddonSchemaDesignerClient _client = null!;
	private BusinessRuleAddonService _service = null!;
	private AddonSchemaDto? _savedSchema;

	[SetUp]
	public void SetUp() {
		_savedSchema = null;
		_client = Substitute.For<IAddonSchemaDesignerClient>();
		_client.GetSchema(Arg.Any<AddonGetRequestDto>()).Returns(_ => BuildSchema());
		_client
			.When(client => client.SaveSchema(Arg.Any<AddonSchemaDto>()))
			.Do(callInfo => _savedSchema = callInfo.Arg<AddonSchemaDto>());
		_service = new BusinessRuleAddonService(_client);
	}

	[Test]
	[Category("Unit")]
	[Description("Replaces the matched rule in place (order preserved), removes its old autogenerated children, appends the regenerated children, upserts the caption resource, and persists the whole batch with exactly one SaveSchema, ResetClientScriptCache, and BuildConfiguration.")]
	public void UpdateRules_Should_Replace_Rule_In_Place_And_Regenerate_Children_When_Name_Matches() {
		// Arrange
		BusinessRuleMetadataDto generatedParent = CreateGeneratedRule("Rule_A", caption: "New caption");
		string generatedParentUId = generatedParent.UId;
		BusinessRuleMetadataDto generatedChild = CreateGeneratedRule(
			$"Autogenerated_{generatedParentUId}_ClearValue",
			caption: $"ChildRule-{generatedParentUId}-ClearValue");
		generatedChild.ParentUId = generatedParentUId;

		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.UpdateRules(
			new AddonGetRequestDto(),
			[new BusinessRuleUpdateItem("Rule_A", false, [generatedParent, generatedChild])]);

		// Assert
		results.Should().ContainSingle(because: "one input item yields one outcome");
		results[0].Success.Should().BeTrue(because: "the rule name matched and the save succeeded");
		results[0].RuleName.Should().Be("Rule_A", because: "the outcome reports the updated rule name");
		_savedSchema.Should().NotBeNull(because: "a matched update must persist the mutated metadata");
		using JsonDocument metaData = JsonDocument.Parse(_savedSchema!.MetaData);
		JsonElement[] rules = [.. metaData.RootElement.GetProperty("rules").EnumerateArray()];
		rules.Should().HaveCount(3,
			because: "the replaced parent stays in place, the old child is removed, Rule_B survives, and the new child is appended");
		rules[0].GetProperty("name").GetString().Should().Be("Rule_A",
			because: "the replacement must keep the matched rule's position in the array");
		rules[0].GetProperty("uId").GetString().Should().Be(RuleAUId,
			because: "the grafter preserves the persisted rule uId on the replacement");
		rules[0].GetProperty("enabled").GetBoolean().Should().BeFalse(
			because: "the caller's explicit enabled=false intent must be applied");
		rules[1].GetProperty("name").GetString().Should().Be("Rule_B",
			because: "unrelated rules keep their position and content");
		rules[2].GetProperty("parentUId").GetString().Should().Be(RuleAUId,
			because: "the regenerated child is re-anchored to the preserved parent uId and appended");
		rules[2].GetProperty("name").GetString().Should().Be($"Autogenerated_{RuleAUId}_ClearValue",
			because: "the parent uId embedded in the regenerated child name is rewritten");
		rules.Should().NotContain(rule => rule.GetProperty("uId").GetString() == ChildAUId,
			because: "the old autogenerated child of the replaced rule must be removed");
		_savedSchema.Resources.Should().Contain(resource =>
				resource.Key == $"{RuleAUId}.Caption" && resource.Value[0].Value == "New caption",
			because: "the caption resource of the replaced rule must be upserted with the new caption");
		_savedSchema.Resources.Should().NotContain(resource => resource.Key == $"{ChildAUId}.Caption",
			because: "caption resources of removed children must be deleted");
		_client.Received(1).SaveSchema(Arg.Any<AddonSchemaDto>());
		_client.Received(1).ResetClientScriptCache();
		_client.Received(1).BuildConfiguration();
	}

	[Test]
	[Category("Unit")]
	[Description("Reports a per-item failure for an unknown rule name and performs no save when it is the only item of the batch.")]
	public void UpdateRules_Should_Report_Per_Item_Failure_Without_Saving_When_Name_Is_Unknown() {
		// Arrange
		BusinessRuleMetadataDto generatedParent = CreateGeneratedRule("Missing_Rule");

		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.UpdateRules(
			new AddonGetRequestDto(),
			[new BusinessRuleUpdateItem("Missing_Rule", null, [generatedParent])]);

		// Assert
		results.Should().ContainSingle(because: "one input item yields one outcome");
		results[0].Success.Should().BeFalse(because: "no persisted rule matches the requested name");
		results[0].Error.Should().Be("Business rule 'Missing_Rule' was not found.",
			because: "the failure must name the missing rule so the caller can correct it");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
		_client.DidNotReceive().ResetClientScriptCache();
		_client.DidNotReceive().BuildConfiguration();
	}

	[Test]
	[Category("Unit")]
	[Description("Isolates an unknown-name failure inside a mixed batch: the matched rule is still updated with a single save while the unknown name fails alone.")]
	public void UpdateRules_Should_Isolate_Unknown_Name_When_Batch_Has_Matched_Rules() {
		// Arrange
		BusinessRuleMetadataDto matchedRule = CreateGeneratedRule("Rule_A");
		BusinessRuleMetadataDto unmatchedRule = CreateGeneratedRule("Missing_Rule");

		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.UpdateRules(
			new AddonGetRequestDto(),
			[
				new BusinessRuleUpdateItem("Rule_A", null, [matchedRule]),
				new BusinessRuleUpdateItem("Missing_Rule", null, [unmatchedRule])
			]);

		// Assert
		results.Should().HaveCount(2, because: "every input item gets an outcome in input order");
		results[0].Success.Should().BeTrue(because: "the matched rule must still be updated despite the failing sibling");
		results[1].Success.Should().BeFalse(because: "no persisted rule matches the second name");
		results[1].Error.Should().Contain("Missing_Rule", because: "the failure must name the missing rule");
		_client.Received(1).SaveSchema(Arg.Any<AddonSchemaDto>());
	}

	[Test]
	[Category("Unit")]
	[Description("Rejects a repeated rule name inside one update batch: the first occurrence applies, the repeat fails per-item so the second definition cannot silently graft against the first item's replacement.")]
	public void UpdateRules_Should_Reject_Repeated_Name_Within_One_Batch() {
		// Arrange
		BusinessRuleMetadataDto firstDefinition = CreateGeneratedRule("Rule_A", caption: "First definition");
		BusinessRuleMetadataDto secondDefinition = CreateGeneratedRule("Rule_A", caption: "Second definition");

		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.UpdateRules(
			new AddonGetRequestDto(),
			[
				new BusinessRuleUpdateItem("Rule_A", null, [firstDefinition]),
				new BusinessRuleUpdateItem("Rule_A", null, [secondDefinition])
			]);

		// Assert
		results.Should().HaveCount(2, because: "every input item gets an outcome in input order");
		results[0].Success.Should().BeTrue(because: "the first occurrence of the name applies normally");
		results[1].Success.Should().BeFalse(because: "the repeated name must not double-apply within one batch");
		results[1].Error.Should().Contain("more than once", because: "the failure must explain the in-batch repeat");
		_savedSchema.Should().NotBeNull(because: "the first occurrence still persists");
		_savedSchema!.Resources.Should().Contain(resource =>
				resource.Key == $"{RuleAUId}.Caption" && resource.Value[0].Value == "First definition",
			because: "only the first definition's caption must be applied");
	}

	[Test]
	[Category("Unit")]
	[Description("Fails update and delete items per-item when the persisted metadata carries more than one parent rule with the requested name, instead of silently operating on an arbitrary match.")]
	public void UpdateRules_And_DeleteRules_Should_Fail_Item_When_Persisted_Name_Is_Ambiguous() {
		// Arrange - two parent rules sharing the same name (designer-authored duplicates)
		_client.GetSchema(Arg.Any<AddonGetRequestDto>()).Returns(_ => new AddonSchemaDto {
			MetaData = $$"""
				{
				  "typeName": "{{BusinessRuleConstants.BusinessRulesMetadataTypeName}}",
				  "rules": [
				    { "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}", "uId": "{{RuleAUId}}", "name": "Dup_Rule", "cases": [], "triggers": [] },
				    { "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}", "uId": "{{RuleBUId}}", "name": "dup_rule", "cases": [], "triggers": [] }
				  ]
				}
				""",
			Resources = []
		});
		BusinessRuleMetadataDto generatedRule = CreateGeneratedRule("Dup_Rule");

		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> updateResults = _service.UpdateRules(
			new AddonGetRequestDto(),
			[new BusinessRuleUpdateItem("Dup_Rule", null, [generatedRule])]);
		IReadOnlyList<BusinessRuleBatchItemResult> deleteResults = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Dup_Rule"]);

		// Assert
		updateResults[0].Success.Should().BeFalse(
			because: "an ambiguous name must not update an arbitrary rule");
		updateResults[0].Error.Should().Contain("more than one rule",
			because: "the update failure must explain the ambiguity");
		deleteResults[0].Success.Should().BeFalse(
			because: "an ambiguous name must not delete an arbitrary rule");
		deleteResults[0].Error.Should().Contain("more than one rule",
			because: "the delete failure must explain the ambiguity");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	[Test]
	[Category("Unit")]
	[Description("Marks every pending (matched) item failed with the save error when the single batch save throws, preserving single-save atomicity.")]
	public void UpdateRules_Should_Fail_All_Pending_Items_With_Save_Error_When_SaveSchema_Throws() {
		// Arrange
		_client
			.When(client => client.SaveSchema(Arg.Any<AddonSchemaDto>()))
			.Do(_ => throw new InvalidOperationException("Add-on save failed."));

		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.UpdateRules(
			new AddonGetRequestDto(),
			[
				new BusinessRuleUpdateItem("Rule_A", null, [CreateGeneratedRule("Rule_A")]),
				new BusinessRuleUpdateItem("Rule_B", null, [CreateGeneratedRule("Rule_B")])
			]);

		// Assert
		results.Should().HaveCount(2, because: "every input item still gets an outcome");
		results.Should().OnlyContain(result => !result.Success,
			because: "the single batch save failed, so no item can report success");
		results.Should().OnlyContain(result => result.Error == "Add-on save failed.",
			because: "all pending items share the same save error under single-save atomicity");
	}

	[Test]
	[Category("Unit")]
	[Description("Deletes the matched rule together with its autogenerated children and their caption resources, saving once for the batch.")]
	public void DeleteRules_Should_Remove_Rule_Children_And_Caption_Resources_When_Name_Matches() {
		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Rule_A"]);

		// Assert
		results.Should().ContainSingle(because: "one input name yields one outcome");
		results[0].Success.Should().BeTrue(because: "the rule name matched and the save succeeded");
		_savedSchema.Should().NotBeNull(because: "a matched delete must persist the mutated metadata");
		using JsonDocument metaData = JsonDocument.Parse(_savedSchema!.MetaData);
		JsonElement[] rules = [.. metaData.RootElement.GetProperty("rules").EnumerateArray()];
		rules.Should().ContainSingle(because: "the deleted rule and its autogenerated child are both removed");
		rules[0].GetProperty("name").GetString().Should().Be("Rule_B",
			because: "unrelated rules survive the delete");
		_savedSchema.Resources.Should().NotContain(resource => resource.Key == $"{RuleAUId}.Caption",
			because: "the deleted rule's caption resource must be removed");
		_savedSchema.Resources.Should().NotContain(resource => resource.Key == $"{ChildAUId}.Caption",
			because: "the deleted child's caption resource must be removed");
		_savedSchema.Resources.Should().Contain(resource => resource.Key == $"{RuleBUId}.Caption",
			because: "unrelated caption resources survive the delete");
		_client.Received(1).SaveSchema(Arg.Any<AddonSchemaDto>());
		_client.Received(1).ResetClientScriptCache();
		_client.Received(1).BuildConfiguration();
	}

	[Test]
	[Category("Unit")]
	[Description("Isolates blank and unknown names as per-item failures inside a mixed delete batch while the matched name still deletes with a single save.")]
	public void DeleteRules_Should_Isolate_Blank_And_Unknown_Names_When_Batch_Has_Mixed_Entries() {
		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Rule_A", " ", "Missing_Rule"]);

		// Assert
		results.Should().HaveCount(3, because: "every input name gets an outcome in input order");
		results[0].Success.Should().BeTrue(because: "the first name matched a persisted rule");
		results[1].Success.Should().BeFalse(because: "a whitespace name cannot match any rule");
		results[1].Error.Should().Be("Business rule name is required.",
			because: "blank names fail with the dedicated required-name message");
		results[2].Success.Should().BeFalse(because: "no persisted rule matches the third name");
		results[2].Error.Should().Be("Business rule 'Missing_Rule' was not found.",
			because: "unknown names fail with the not-found message naming the rule");
		_client.Received(1).SaveSchema(Arg.Any<AddonSchemaDto>());
	}

	[Test]
	[Category("Unit")]
	[Description("Performs no save when no delete entry matches a persisted rule.")]
	public void DeleteRules_Should_Not_Save_When_No_Names_Match() {
		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Missing_Rule"]);

		// Assert
		results.Should().ContainSingle(because: "one input name yields one outcome");
		results[0].Success.Should().BeFalse(because: "no persisted rule matches the requested name");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
		_client.DidNotReceive().BuildConfiguration();
	}

	[Test]
	[Category("Unit")]
	[Description("Reads every parent rule persisted on the target schema into read models, skipping autogenerated children.")]
	public void ReadRules_Should_Return_Models_From_Metadata_When_Rules_Exist() {
		// Act
		IReadOnlyList<BusinessRuleReadModel> models = _service.ReadRules(new AddonGetRequestDto());

		// Assert
		models.Should().HaveCount(2,
			because: "the two parent rules are returned while the autogenerated child is folded away");
		models.Select(model => model.Name).Should().Equal(["Rule_A", "Rule_B"],
			because: "read models come back in persisted order");
		_client.Received(1).GetSchema(Arg.Any<AddonGetRequestDto>());
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	[Test]
	[Category("Unit")]
	[Description("Returns an empty list when the target schema carries no add-on metadata yet.")]
	public void ReadRules_Should_Return_Empty_List_When_Metadata_Is_Empty() {
		// Arrange
		_client.GetSchema(Arg.Any<AddonGetRequestDto>()).Returns(new AddonSchemaDto {
			MetaData = string.Empty,
			Resources = []
		});

		// Act
		IReadOnlyList<BusinessRuleReadModel> models = _service.ReadRules(new AddonGetRequestDto());

		// Assert
		models.Should().BeEmpty(because: "a schema without persisted metadata has no rules to read");
	}

	[Test]
	[Category("Unit")]
	[Description("Rejects appending a rule whose explicit name collides with a rule already persisted on the schema, without saving.")]
	public void AppendRules_Should_Throw_When_Explicit_Name_Collides_With_Existing_Rule() {
		// Act
		Action act = () => _service.AppendRules(
			new AddonGetRequestDto(),
			[CreateGeneratedRule("Rule_A")]);

		// Assert
		act.Should().Throw<InvalidOperationException>()
			.WithMessage("*Rule_A*",
				because: "the duplicate-name error must name the colliding rule so the caller can switch to update");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	[Test]
	[Category("Unit")]
	[Description("Rejects a batch that repeats the same explicit rule name inside itself, without saving.")]
	public void AppendRules_Should_Throw_When_Batch_Repeats_Explicit_Name() {
		// Act
		Action act = () => _service.AppendRules(
			new AddonGetRequestDto(),
			[CreateGeneratedRule("Dup_Rule"), CreateGeneratedRule("Dup_Rule")]);

		// Assert
		act.Should().Throw<InvalidOperationException>()
			.WithMessage("*Dup_Rule*",
				because: "an in-batch duplicate breaks the name-based update/delete match key just like an existing collision");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	private static AddonSchemaDto BuildSchema() =>
		new() {
			MetaData = $$"""
				{
				  "typeName": "{{BusinessRuleConstants.BusinessRulesMetadataTypeName}}",
				  "rules": [
				    {
				      "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}",
				      "uId": "{{RuleAUId}}",
				      "name": "Rule_A",
				      "enabled": true,
				      "caption": "Rule A",
				      "cases": [
				        {
				          "typeName": "{{BusinessRuleConstants.BusinessRuleCaseTypeName}}",
				          "uId": "aaaaaaaa-0000-0000-0000-00000000000a",
				          "condition": {
				            "typeName": "{{BusinessRuleConstants.BusinessRuleGroupConditionTypeName}}",
				            "uId": "aaaaaaaa-0000-0000-0000-00000000000b",
				            "logicalOperation": 1,
				            "conditions": []
				          },
				          "actions": []
				        }
				      ],
				      "triggers": []
				    },
				    {
				      "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}",
				      "uId": "{{ChildAUId}}",
				      "name": "Autogenerated_{{RuleAUId}}_ClearValue",
				      "enabled": true,
				      "caption": "ChildRule-{{RuleAUId}}-ClearValue",
				      "parentUId": "{{RuleAUId}}",
				      "cases": [],
				      "triggers": []
				    },
				    {
				      "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}",
				      "uId": "{{RuleBUId}}",
				      "name": "Rule_B",
				      "enabled": true,
				      "caption": "Rule B",
				      "cases": [
				        {
				          "typeName": "{{BusinessRuleConstants.BusinessRuleCaseTypeName}}",
				          "uId": "bbbbbbbb-0000-0000-0000-00000000000a",
				          "actions": []
				        }
				      ],
				      "triggers": []
				    }
				  ]
				}
				""",
			Resources = [
				CreateCaptionResource(RuleAUId, "Rule A"),
				CreateCaptionResource(ChildAUId, "Child caption"),
				CreateCaptionResource(RuleBUId, "Rule B")
			]
		};

	private static AddonResourceDto CreateCaptionResource(string ruleUId, string caption) =>
		new() {
			Key = $"{ruleUId}.Caption",
			Value = [
				new AddonResourceValueDto { Key = "en-US", Value = caption }
			]
		};

	private static BusinessRuleMetadataDto CreateGeneratedRule(string name, string? caption = "Generated caption") =>
		new() {
			UId = Guid.NewGuid().ToString(),
			Name = name,
			Enabled = true,
			Caption = caption,
			Cases = [
				new BusinessRuleCaseMetadataDto {
					UId = Guid.NewGuid().ToString(),
					Condition = new BusinessRuleGroupConditionMetadataDto {
						TypeName = BusinessRuleConstants.BusinessRuleGroupConditionTypeName,
						UId = Guid.NewGuid().ToString(),
						LogicalOperation = BusinessRuleConstants.LogicalAnd,
						Conditions = []
					},
					Actions = []
				}
			],
			Triggers = []
		};
}
