using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Clio.Command.AddonSchemaDesigner;
using Clio.Command.BusinessRules;
using FluentAssertions;
using NSubstitute;
using NUnit.Framework;

namespace Clio.Tests.Command;

[TestFixture]
[Property("Module", "Command")]
public sealed class BusinessRuleAddonServiceTests {

	private const string RuleAUId = "11111111-1111-1111-1111-111111111111";
	private const string ChildAUId = "22222222-2222-2222-2222-222222222222";
	private const string RuleBUId = "33333333-3333-3333-3333-333333333333";

	private IAddonSchemaDesignerClient _client = null!;
	private BusinessRuleAddonService _service = null!;
	private AddonSchemaDto? _savedSchema;

	[SetUp]
	public void SetUp() {
		_savedSchema = null;
		_client = Substitute.For<IAddonSchemaDesignerClient>();
		_client.GetSchema(Arg.Any<AddonGetRequestDto>()).Returns(_ => BuildSchema());
		_client
			.When(client => client.SaveSchema(Arg.Any<AddonSchemaDto>()))
			.Do(callInfo => _savedSchema = callInfo.Arg<AddonSchemaDto>());
		_service = new BusinessRuleAddonService(_client);
	}

	[Test]
	[Category("Unit")]
	[Description("Fails a delete item when the persisted metadata carries more than one parent rule with the requested name, instead of silently operating on an arbitrary match.")]
	public void DeleteRules_Should_Fail_Item_When_Persisted_Name_Is_Ambiguous() {
		// Arrange - two parent rules sharing the same name (designer-authored duplicates)
		_client.GetSchema(Arg.Any<AddonGetRequestDto>()).Returns(_ => new AddonSchemaDto {
			MetaData = $$"""
				{
				  "typeName": "{{BusinessRuleConstants.BusinessRulesMetadataTypeName}}",
				  "rules": [
				    { "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}", "uId": "{{RuleAUId}}", "name": "Dup_Rule", "cases": [], "triggers": [] },
				    { "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}", "uId": "{{RuleBUId}}", "name": "dup_rule", "cases": [], "triggers": [] }
				  ]
				}
				""",
			Resources = []
		});

		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> deleteResults = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Dup_Rule"]);

		// Assert
		deleteResults[0].Success.Should().BeFalse(
			because: "an ambiguous name must not delete an arbitrary rule");
		deleteResults[0].Error.Should().Contain("more than one rule",
			because: "the delete failure must explain the ambiguity");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	[Test]
	[Category("Unit")]
	[Description("Deletes the matched rule together with its autogenerated children and their caption resources, saving once for the batch.")]
	public void DeleteRules_Should_Remove_Rule_Children_And_Caption_Resources_When_Name_Matches() {
		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Rule_A"]);

		// Assert
		results.Should().ContainSingle(because: "one input name yields one outcome");
		results[0].Success.Should().BeTrue(because: "the rule name matched and the save succeeded");
		_savedSchema.Should().NotBeNull(because: "a matched delete must persist the mutated metadata");
		using JsonDocument metaData = JsonDocument.Parse(_savedSchema!.MetaData);
		JsonElement[] rules = [.. metaData.RootElement.GetProperty("rules").EnumerateArray()];
		rules.Should().ContainSingle(because: "the deleted rule and its autogenerated child are both removed");
		rules[0].GetProperty("name").GetString().Should().Be("Rule_B",
			because: "unrelated rules survive the delete");
		_savedSchema.Resources.Should().NotContain(resource => resource.Key == $"{RuleAUId}.Caption",
			because: "the deleted rule's caption resource must be removed");
		_savedSchema.Resources.Should().NotContain(resource => resource.Key == $"{ChildAUId}.Caption",
			because: "the deleted child's caption resource must be removed");
		_savedSchema.Resources.Should().Contain(resource => resource.Key == $"{RuleBUId}.Caption",
			because: "unrelated caption resources survive the delete");
		_client.Received(1).SaveSchema(Arg.Any<AddonSchemaDto>());
		_client.Received(1).ResetClientScriptCache();
		_client.Received(1).BuildConfiguration();
	}

	[Test]
	[Category("Unit")]
	[Description("Isolates blank and unknown names as per-item failures inside a mixed delete batch while the matched name still deletes with a single save.")]
	public void DeleteRules_Should_Isolate_Blank_And_Unknown_Names_When_Batch_Has_Mixed_Entries() {
		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Rule_A", " ", "Missing_Rule"]);

		// Assert
		results.Should().HaveCount(3, because: "every input name gets an outcome in input order");
		results[0].Success.Should().BeTrue(because: "the first name matched a persisted rule");
		results[1].Success.Should().BeFalse(because: "a whitespace name cannot match any rule");
		results[1].Error.Should().Be("Business rule name is required.",
			because: "blank names fail with the dedicated required-name message");
		results[2].Success.Should().BeFalse(because: "no persisted rule matches the third name");
		results[2].Error.Should().Be("Business rule 'Missing_Rule' was not found.",
			because: "unknown names fail with the not-found message naming the rule");
		_client.Received(1).SaveSchema(Arg.Any<AddonSchemaDto>());
	}

	[Test]
	[Category("Unit")]
	[Description("Performs no save when no delete entry matches a persisted rule.")]
	public void DeleteRules_Should_Not_Save_When_No_Names_Match() {
		// Act
		IReadOnlyList<BusinessRuleBatchItemResult> results = _service.DeleteRules(
			new AddonGetRequestDto(),
			["Missing_Rule"]);

		// Assert
		results.Should().ContainSingle(because: "one input name yields one outcome");
		results[0].Success.Should().BeFalse(because: "no persisted rule matches the requested name");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
		_client.DidNotReceive().BuildConfiguration();
	}

	[Test]
	[Category("Unit")]
	[Description("Reads every parent rule persisted on the target schema into friendly rules, skipping autogenerated children.")]
	public void ReadRules_Should_Return_Models_From_Metadata_When_Rules_Exist() {
		// Act
		IReadOnlyList<BusinessRule> models = _service.ReadRules(new AddonGetRequestDto());

		// Assert
		models.Should().HaveCount(2,
			because: "the two parent rules are returned while the autogenerated child is folded away");
		models.Select(model => model.Name).Should().Equal(["Rule_A", "Rule_B"],
			because: "rules come back in persisted order");
		_client.Received(1).GetSchema(Arg.Any<AddonGetRequestDto>());
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	[Test]
	[Category("Unit")]
	[Description("Returns an empty list when the target schema carries no add-on metadata yet.")]
	public void ReadRules_Should_Return_Empty_List_When_Metadata_Is_Empty() {
		// Arrange
		_client.GetSchema(Arg.Any<AddonGetRequestDto>()).Returns(new AddonSchemaDto {
			MetaData = string.Empty,
			Resources = []
		});

		// Act
		IReadOnlyList<BusinessRule> models = _service.ReadRules(new AddonGetRequestDto());

		// Assert
		models.Should().BeEmpty(because: "a schema without persisted metadata has no rules to read");
	}

	[Test]
	[Category("Unit")]
	[Description("Rejects appending a rule whose explicit name collides with a rule already persisted on the schema, without saving.")]
	public void AppendRules_Should_Throw_When_Explicit_Name_Collides_With_Existing_Rule() {
		// Act
		Action act = () => _service.AppendRules(
			new AddonGetRequestDto(),
			[CreateGeneratedRule("Rule_A")]);

		// Assert
		act.Should().Throw<InvalidOperationException>()
			.WithMessage("*Rule_A*",
				because: "the duplicate-name error must name the colliding rule so the caller can switch to update");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	[Test]
	[Category("Unit")]
	[Description("Rejects a batch that repeats the same explicit rule name inside itself, without saving.")]
	public void AppendRules_Should_Throw_When_Batch_Repeats_Explicit_Name() {
		// Act
		Action act = () => _service.AppendRules(
			new AddonGetRequestDto(),
			[CreateGeneratedRule("Dup_Rule"), CreateGeneratedRule("Dup_Rule")]);

		// Assert
		act.Should().Throw<InvalidOperationException>()
			.WithMessage("*Dup_Rule*",
				because: "an in-batch duplicate breaks the name-based update/delete match key just like an existing collision");
		_client.DidNotReceiveWithAnyArgs().SaveSchema(default!);
	}

	private static AddonSchemaDto BuildSchema() =>
		new() {
			MetaData = $$"""
				{
				  "typeName": "{{BusinessRuleConstants.BusinessRulesMetadataTypeName}}",
				  "rules": [
				    {
				      "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}",
				      "uId": "{{RuleAUId}}",
				      "name": "Rule_A",
				      "enabled": true,
				      "caption": "Rule A",
				      "cases": [
				        {
				          "typeName": "{{BusinessRuleConstants.BusinessRuleCaseTypeName}}",
				          "uId": "aaaaaaaa-0000-0000-0000-00000000000a",
				          "condition": {
				            "typeName": "{{BusinessRuleConstants.BusinessRuleGroupConditionTypeName}}",
				            "uId": "aaaaaaaa-0000-0000-0000-00000000000b",
				            "logicalOperation": 1,
				            "conditions": []
				          },
				          "actions": []
				        }
				      ],
				      "triggers": []
				    },
				    {
				      "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}",
				      "uId": "{{ChildAUId}}",
				      "name": "Autogenerated_{{RuleAUId}}_ClearValue",
				      "enabled": true,
				      "caption": "ChildRule-{{RuleAUId}}-ClearValue",
				      "parentUId": "{{RuleAUId}}",
				      "cases": [],
				      "triggers": []
				    },
				    {
				      "typeName": "{{BusinessRuleConstants.BusinessRuleTypeName}}",
				      "uId": "{{RuleBUId}}",
				      "name": "Rule_B",
				      "enabled": true,
				      "caption": "Rule B",
				      "cases": [
				        {
				          "typeName": "{{BusinessRuleConstants.BusinessRuleCaseTypeName}}",
				          "uId": "bbbbbbbb-0000-0000-0000-00000000000a",
				          "actions": []
				        }
				      ],
				      "triggers": []
				    }
				  ]
				}
				""",
			Resources = [
				CreateCaptionResource(RuleAUId, "Rule A"),
				CreateCaptionResource(ChildAUId, "Child caption"),
				CreateCaptionResource(RuleBUId, "Rule B")
			]
		};

	private static AddonResourceDto CreateCaptionResource(string ruleUId, string caption) =>
		new() {
			Key = $"{ruleUId}.Caption",
			Value = [
				new AddonResourceValueDto { Key = "en-US", Value = caption }
			]
		};

	private static BusinessRuleMetadataDto CreateGeneratedRule(string name, string? caption = "Generated caption") =>
		new() {
			UId = Guid.NewGuid().ToString(),
			Name = name,
			Enabled = true,
			Caption = caption,
			Cases = [
				new BusinessRuleCaseMetadataDto {
					UId = Guid.NewGuid().ToString(),
					Condition = new BusinessRuleGroupConditionMetadataDto {
						TypeName = BusinessRuleConstants.BusinessRuleGroupConditionTypeName,
						UId = Guid.NewGuid().ToString(),
						LogicalOperation = BusinessRuleConstants.LogicalAnd,
						Conditions = []
					},
					Actions = []
				}
			],
			Triggers = []
		};
}
