using System.Text.Json.Serialization;

namespace Clio.Command.McpServer.Tools;

/// <summary>
/// ENG-90312 Phase 2 — abstract base for the consolidated <c>clio-run</c> meta-tool.
/// Per-command derived records carry their existing args fields. The discriminator
/// property is <c>command</c>; the MCP SDK publishes the resulting polymorphic schema
/// as JSON Schema <c>anyOf</c> in <c>tools/list</c>.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "command")]
[JsonDerivedType(typeof(AddItemModelRunArgs), "add-item-model")]
[JsonDerivedType(typeof(AddPackageRunArgs), "add-package")]
[JsonDerivedType(typeof(AddPackageDependencyRunArgs), "add-package-dependency")]
[JsonDerivedType(typeof(AppSectionRunArgs), "app-section")]
[JsonDerivedType(typeof(ApplicationCreateRunArgs), "create-app")]
[JsonDerivedType(typeof(ApplicationDeleteRunArgs), "delete-app")]
[JsonDerivedType(typeof(ClearRedisDbRunArgs), "clear-redis-db")]
[JsonDerivedType(typeof(CompileCreatioRunArgs), "compile-creatio")]
[JsonDerivedType(typeof(CreateDataBindingDbRunArgs), "create-data-binding-db")]
[JsonDerivedType(typeof(CreateDataBindingRunArgs), "create-data-binding")]
[JsonDerivedType(typeof(CreateEntityBusinessRuleRunArgs), "create-entity-business-rule")]
[JsonDerivedType(typeof(CreatePageBusinessRuleRunArgs), "create-page-business-rule")]
[JsonDerivedType(typeof(CreateTestProjectRunArgs), "new-test-project")]
[JsonDerivedType(typeof(CreateUiProjectRunArgs), "create-ui-project")]
[JsonDerivedType(typeof(CreateUserTaskRunArgs), "create-user-task")]
[JsonDerivedType(typeof(CreateWorkspaceRunArgs), "create-workspace")]
[JsonDerivedType(typeof(DataBindingRowDbRunArgs), "data-binding-row-db")]
[JsonDerivedType(typeof(DataBindingRowRunArgs), "data-binding-row")]
[JsonDerivedType(typeof(DataForgeInitializeRunArgs), "dataforge-initialize")]
[JsonDerivedType(typeof(DataForgeUpdateRunArgs), "dataforge-update")]
[JsonDerivedType(typeof(DeleteSchemaRunArgs), "delete-schema")]
[JsonDerivedType(typeof(DeleteSkillRunArgs), "delete-adac")]
[JsonDerivedType(typeof(DeployCreatioRunArgs), "deploy-creatio")]
[JsonDerivedType(typeof(DownloadConfigurationRunArgs), "download-configuration")]
[JsonDerivedType(typeof(FinishHotfixRunArgs), "finish-hotfix")]
[JsonDerivedType(typeof(GenerateProcessModelRunArgs), "generate-process-model")]
[JsonDerivedType(typeof(GenerateSourceCodeRunArgs), "generate-source-code")]
[JsonDerivedType(typeof(InstallApplicationRunArgs), "install-application")]
[JsonDerivedType(typeof(InstallGateRunArgs), "install-gate")]
[JsonDerivedType(typeof(InstallSkillsRunArgs), "install-adac")]
[JsonDerivedType(typeof(LinkFromRepositoryRunArgs), "link-from-repository")]
[JsonDerivedType(typeof(ModifyEntitySchemaColumnRunArgs), "modify-entity-schema-column")]
[JsonDerivedType(typeof(ModifyUserTaskParametersRunArgs), "modify-user-task-parameters")]
[JsonDerivedType(typeof(ODataCreateRunArgs), "odata-create")]
[JsonDerivedType(typeof(ODataDeleteRunArgs), "odata-delete")]
[JsonDerivedType(typeof(ODataUpdateRunArgs), "odata-update")]
[JsonDerivedType(typeof(PageCreateRunArgs), "create-page")]
[JsonDerivedType(typeof(PageGetRunArgs), "get-page")]
[JsonDerivedType(typeof(PageSyncRunArgs), "sync-pages")]
[JsonDerivedType(typeof(PageUpdateRunArgs), "update-page")]
[JsonDerivedType(typeof(PkgModeRunArgs), "pkg-mode")]
[JsonDerivedType(typeof(PushWorkspaceRunArgs), "push-workspace")]
[JsonDerivedType(typeof(RegWebAppRunArgs), "reg-web-app")]
[JsonDerivedType(typeof(RestartCreatioRunArgs), "restart-creatio")]
[JsonDerivedType(typeof(RestoreDbRunArgs), "restore-db")]
[JsonDerivedType(typeof(RestoreWorkspaceRunArgs), "restore-workspace")]
[JsonDerivedType(typeof(SchemaCreateRunArgs), "create-schema")]
[JsonDerivedType(typeof(SchemaSyncRunArgs), "sync-schemas")]
[JsonDerivedType(typeof(SchemaUpdateRunArgs), "update-schema")]
[JsonDerivedType(typeof(SetFsmModeRunArgs), "set-fsm-mode")]
[JsonDerivedType(typeof(SqlSchemaInstallRunArgs), "install-sql-schema")]
[JsonDerivedType(typeof(StartCreatioRunArgs), "start-creatio")]
[JsonDerivedType(typeof(StopAllCreatioRunArgs), "stop-all-creatio")]
[JsonDerivedType(typeof(StopCreatioRunArgs), "stop-creatio")]
[JsonDerivedType(typeof(UninstallCreatioRunArgs), "uninstall-creatio")]
[JsonDerivedType(typeof(UpdateSkillRunArgs), "update-adac")]
[JsonDerivedType(typeof(UnlockForHotfixRunArgs), "unlock-for-hotfix")]
[JsonDerivedType(typeof(UpsertSysSettingRunArgs), "upsert-sys-setting")]
public abstract record ClioRunArgs;
