[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:sshd]
command=/usr/sbin/sshd -D -e
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd_err.log

[program:creatio-webhost]
command=/usr/bin/dotnet /app/Terrasoft.WebHost.dll
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/creatio-webhost.log
stderr_logfile=/var/log/supervisor/creatio-webhost_err.log
environment=ASPNETCORE_ENVIRONMENT="Development",DOTNET_PRINT_TELEMETRY_MESSAGE="false"

[program:code-server]
command=/usr/local/bin/code-server --bind-addr 0.0.0.0:8080 --auth password /app
autostart=true
autorestart=true
environment=PASSWORD="Supervisor"
stdout_logfile=/var/log/supervisor/code-server.log
stderr_logfile=/var/log/supervisor/code-server_err.log
