kind: PersistentVolume
apiVersion: v1
metadata:
  name: clio-mssql-data-pv
  labels:
    type: local
    app: clio-mssql
spec:
  storageClassName: clio-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/clio-infrastructure/mssql"