using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Activation;
using System.ServiceModel.Web;
using ATF.Repository;
using cliogate.Files.cs.Dto;
using ClioGate.Functions.SQL;
using Cliogate.Services;
using Common.Logging;
using Newtonsoft.Json;
using Terrasoft.Common;
using Terrasoft.Core;
using Terrasoft.Core.Configuration;
using Terrasoft.Core.ConfigurationBuild;
using Terrasoft.Core.DB;
using Terrasoft.Core.Entities;
using Terrasoft.Core.Factories;
using Terrasoft.Core.Packages;
using Terrasoft.Core.ServiceModelContract;
using Terrasoft.Core.Store;
using Terrasoft.Web.Common;
using Terrasoft.Web.Http.Abstractions;
using cliogate.Files.cs; // Add this line to include the LiveLogger namespace
using Exception = System.Exception;
using System.IO.Compression;

#if NETSTANDARD2_0
using System.Globalization;
using Terrasoft.Web.Http.Abstractions;
#endif

namespace cliogate.Files.cs
{
	#region Class: CompilationResult

	[DataContract]
	public class CompilationResult
	{

		#region Properties: Public

		[JsonProperty("compilerErrors")]
		public CompilerErrorCollection CompilerErrors { get; set; }

		[JsonProperty("status")]
		public BuildResultType Status { get; set; }

		#endregion

	}

	#endregion

	#region Class: CreatioApiGateway

	[ServiceContract]
	[AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Required)]
	public class CreatioApiGateway : BaseService
	{

		private readonly UserConnection _userConnection;
		public CreatioApiGateway(){
			_userConnection = ClassFactory.Get<UserConnection>();
		}
		private HttpContext HttpContext => HttpContextAccessor.GetInstance();
		#region Fields: Private

		private readonly ILog _log = LogManager.GetLogger(typeof(CreatioApiGateway));
		private readonly string splitName = "#OriginalMaintainer:";
		private const string DescriptionColumnName = "Description";

		#endregion

		#region Methods: Private

		private void AssignFileResponseContent(string contentType, long contentLength,
			string contentDisposition){
#if !NETSTANDARD2_0
			WebOperationContext.Current.OutgoingResponse.ContentType = contentType;
			WebOperationContext.Current.OutgoingResponse.ContentLength = contentLength;
			WebOperationContext.Current.OutgoingResponse.Headers.Add("Content-Disposition", contentDisposition);
#else
			HttpContext httpContext = HttpContextAccessor.GetInstance();
			HttpResponse response = httpContext.Response;
			response.ContentType = contentType;
			response.Headers["Content-Length"] = contentLength.ToString(CultureInfo.InvariantCulture);
			response.Headers["Content-Disposition"] = contentDisposition;
#endif
		}

		private void AssignFileResponseContent(long contentLength, string fileName) =>
			AssignFileResponseContent("application/octet-stream", contentLength,
				$"attachment; filename=\"{fileName}\"");

		private void CheckCanManageSolution(){
			if (!_userConnection.DBSecurityEngine.GetCanExecuteOperation("CanManageSolution")) {
				throw new Exception("You don't have permission for operation CanManageSolution");
			}
		}
		private void CheckCanManageSysSettings(){
			if (!_userConnection.DBSecurityEngine.GetCanExecuteOperation("CanManageSysSettings")) {
				throw new Exception("You don't have permission for operation CanManageSysSettings");
			}
		}
		
		/// <summary>
		///  Sets the return status code of the HTTP response.
		/// </summary>
		/// <param name="statusCode"></param>
		private void SetReturnStatusCode(HttpStatusCode statusCode){
#if NETFRAMEWORK
			if (WebOperationContext.Current != null) {
				WebOperationContext.Current.OutgoingResponse.StatusCode = statusCode;
			}
			HttpContext.Current.Response.StatusCode = (int)statusCode;
#elif !NETFRAMEWORK
			HttpContext.Response.StatusCode = (int)statusCode;
#endif
		}
		

		private PackageInstallUtilities CreateInstallUtilities(){
			return new PackageInstallUtilities(UserConnection);
		}

		private Stream GetCompressedFolder(string rootRelativePath, string fileName,
			IEnumerable<string> ignoreDirectoriesName = null){
			string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
			string rootDirectoryPath = Path.Combine(baseDirectory, rootRelativePath);
			if (!Directory.Exists(rootDirectoryPath)) {
				return null;
			}
			MemoryStream compressedAutogeneratedFolder
				= CompressionUtilities.GetCompressedFolder(rootDirectoryPath, ignoreDirectoriesName);
			AssignFileResponseContent(compressedAutogeneratedFolder?.Length ?? 0, fileName);
			return compressedAutogeneratedFolder;
		}

		private IEnumerable<Guid> GetEntitySchemasWithNeedUpdateStructure(){
			List<Guid> result = new List<Guid>();
			EntitySchemaQuery esq
				= new EntitySchemaQuery(UserConnection.EntitySchemaManager, "VwSysEntitySchemaInWorkspace");
			esq.AddAllSchemaColumns();
			esq.Filters.LogicalOperation = LogicalOperationStrict.And;
			IEntitySchemaQueryFilterItem needUpdateFilter
				= esq.CreateFilterWithParameters(FilterComparisonType.Equal, "NeedUpdateStructure", true);
			esq.Filters.Add(needUpdateFilter);
			EntityCollection packages = esq.GetEntityCollection(UserConnection);
			foreach (Entity p in packages) {
				Guid schemaUId = p.GetTypedColumnValue<Guid>("UId");
				result.Add(schemaUId);
			}
			return result;
		}

		private T GetPackageAttributeValue<T>(string key, string packageName){
			Select query = new Select(UserConnection)
				.From("SysPackage")
				.Column(key)
				.Where("Name")
				.IsEqual(Column.Parameter(packageName)) as Select;
			T result = query.ExecuteScalar<T>();
			return result;
		}

		/// <summary>
		/// Builds the value stored in the <c>SysPackage.Description</c> column when unlocking a package,
		/// preserving the original maintainer marker. A null <paramref name="originalDescription"/>
		/// (the column is nullable) is treated as an empty string.
		/// </summary>
		internal static string BuildUnlockDescription(string originalDescription, string originalMaintainer,
			string splitMarker){
			originalDescription = originalDescription ?? string.Empty;
			return originalDescription.Contains(splitMarker)
				? originalDescription
				: originalDescription + splitMarker + originalMaintainer;
		}

		/// <summary>
		/// Splits a stored <c>SysPackage.Description</c> value into its human description and the
		/// preserved original maintainer marker when locking a package. A null
		/// <paramref name="originalDescription"/> (the column is nullable) is treated as an empty string,
		/// so the result is always a non-empty array.
		/// </summary>
		internal static string[] SplitLockDescription(string originalDescription, string splitMarker){
			return (originalDescription ?? string.Empty).Split(new[] {splitMarker}, StringSplitOptions.None);
		}

		/// <summary>
		/// Formats package names for a single-line log entry, replacing control and Unicode formatting
		/// characters that could otherwise create misleading log output.
		/// </summary>
		internal static string FormatPackageNamesForLog(IEnumerable<string> packageNames){
			return string.Join(", ", (packageNames ?? Array.Empty<string>()).Select(packageName =>
				new string((packageName ?? string.Empty).Select(character => {
					System.Globalization.UnicodeCategory category = char.GetUnicodeCategory(character);
					return char.IsControl(character) ||
						category == System.Globalization.UnicodeCategory.Format ||
						category == System.Globalization.UnicodeCategory.LineSeparator ||
						category == System.Globalization.UnicodeCategory.ParagraphSeparator
							? ' '
							: character;
				}).ToArray())));
		}

		#endregion

		#region Methods: Public
		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "GetSysSettingValueByCode", BodyStyle = WebMessageBodyStyle.WrappedRequest,
        			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public string GetSysSettingValueByCode(string code){
			CheckCanManageSysSettings();
			bool isValue = SysSettings.TryGetValue(_userConnection, code, out object value);
			
			if(value == null || !isValue) {
				var v  = SysSettings.GetDefValue(_userConnection, code);
				if(v != null) {
					value = v;
					isValue = true;
				}
			}
			
			if(value == null || !isValue) {
				return string.Empty;
			}
			
			
			const string schemaName = "SysSettings";
			Entity sysSettingsEntity = _userConnection.EntitySchemaManager
				.FindInstanceByName(schemaName).CreateEntity(_userConnection);
			
			bool isFetched = sysSettingsEntity.FetchFromDB("Code", code, false);
			string valueTypeName = sysSettingsEntity.GetTypedColumnValue<string>("ValueTypeName");

			string returnValue;
			switch (valueTypeName) {
				case "DateTime":
					DateTime dt1 = DateTime.Parse(value.ToString());
					returnValue = dt1.ToString("dd-MMM-yyyy HH:mm:ss");
					break;
				case "Date":
					DateTime dt2 = DateTime.Parse(value.ToString()).Date;
					returnValue = dt2.ToString("dd-MMM-yyyy");
					break;
				case "Time":
					DateTime dt3 = DateTime.Parse(value.ToString());
					returnValue = dt3.ToString(@"HH:mm:ss");
					break;
				default:
					returnValue = value.ToString();
					break;
			}
			return returnValue;
		}
		
		
		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "CompileWorkspace", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public CompilationResult CompileWorkspace(bool compileModified = false){
			CheckCanManageSolution();
			WorkspaceBuilder workspaceBuilder = WorkspaceBuilderUtility.CreateWorkspaceBuilder(AppConnection);
			CompilerErrorCollection compilerErrors = workspaceBuilder.Rebuild(AppConnection.Workspace,
				out BuildResultType buildResultType);
			IAppConfigurationBuilder configurationBuilder = ClassFactory.Get<IAppConfigurationBuilder>();
			if (compileModified) {
				configurationBuilder.BuildChanged();
			} else {
				configurationBuilder.BuildAll();
			}
			return new CompilationResult {
				Status = buildResultType,
				CompilerErrors = compilerErrors
			};
		}

		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "ExecuteSqlScript", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public string ExecuteSqlScript(string script){
			CheckCanManageSolution();
			return SQLFunctions.ExecuteSQL(script, UserConnection);
		}

		[OperationContract]
		[WebInvoke(Method = "GET", UriTemplate = "GetApiVersion", RequestFormat = WebMessageFormat.Json,
			ResponseFormat = WebMessageFormat.Json, BodyStyle = WebMessageBodyStyle.WrappedRequest)]
		public string GetApiVersion(){
			Version version = typeof(CreatioApiGateway).Assembly.GetName().Version;
			return version.ToString();
		}

		[OperationContract]
		[WebInvoke(Method = "POST", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public Stream GetAutogeneratedFolder(string packageName){
			CheckCanManageSolution();
			string rootRelativePath = Path.Combine("Terrasoft.Configuration", "Pkg",
				packageName, "Autogenerated");
			return GetCompressedFolder(rootRelativePath, $"Autogenerated.{packageName}.gz");
		}

		[OperationContract]
		[WebInvoke(Method = "POST", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public Stream GetConfigurationBinFolder(){
			CheckCanManageSolution();
			string rootRelativePath = Path.Combine("Terrasoft.Configuration", "bin");
			return GetCompressedFolder(rootRelativePath, "Bin.gz");
		}

		[OperationContract]
		[WebInvoke(Method = "POST", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public Stream GetConfigurationLibFolder(){
			CheckCanManageSolution();
			string rootRelativePath = Path.Combine("Terrasoft.Configuration", "Lib");
			return GetCompressedFolder(rootRelativePath, "Lib.gz");
		}

		[OperationContract]
		[WebInvoke(Method = "POST", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public Stream GetCoreBinFolder(){
			CheckCanManageSolution();
			string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
			string rootRelativePath = "bin";

			string[] ignoreDirectoriesName = null;
			if (!Directory.Exists(Path.Combine(baseDirectory, "bin"))) {
				ignoreDirectoriesName = new[] {
					"AppTemplates", "conf", "Packages", "Resources", "runtimes", "Terrasoft.Configuration", "WebFarm",
					"WorkspaceConsole"
				};
				rootRelativePath = string.Empty;
			}
			return GetCompressedFolder(rootRelativePath, "CoreBin.gz", ignoreDirectoriesName);
		}

		[OperationContract]
		[WebGet(UriTemplate = "GetEntitySchemaModels/{entitySchema}/{fields}", ResponseFormat = WebMessageFormat.Json,
			BodyStyle = WebMessageBodyStyle.Bare)]
		public string GetEntitySchemaModels(string entitySchema, string fields){
			CheckCanManageSolution();
			EntitySchemaModelClassGenerator generator
				= new EntitySchemaModelClassGenerator(UserConnection.EntitySchemaManager);
			List<string> columns = new List<string>();
			if (!string.IsNullOrEmpty(fields)) {
				columns = new List<string>(fields.Split(','));
			}
			Dictionary<string, string> models = generator.Generate(entitySchema, columns);
			return JsonConvert.SerializeObject(models, Formatting.Indented);
		}

		// /rest/CreatioApiGateway/GetPackageFileContent?packageName=CrtBase&filePath=descriptor.json
		[OperationContract]
		[WebInvoke(Method = "GET", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public string GetPackageFileContent(string packageName, string filePath){
			CheckCanManageSolution();

			PackageExplorer packageExplorer = new PackageExplorer(packageName);
			return packageExplorer.GetPackageFileContent(filePath);
		}

		// /rest/CreatioApiGateway/GetPackageFilesDirectoryContent?packageName=CrtBase
		[OperationContract]
		[WebInvoke(Method = "GET", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public IEnumerable<string> GetPackageFilesDirectoryContent(string packageName){
			CheckCanManageSolution();

			PackageExplorer packageExplorer = new PackageExplorer(packageName);
			return packageExplorer.GetPackageFilesDirectoryContent();
		}

		#region Methods: Schema transfer

		/// <summary>
		/// Reads every <c>SysSchema</c> row whose name matches, optionally narrowed to one package and/or one schema
		/// manager.
		/// </summary>
		/// <remarks>
		/// Uses <see cref="Select"/> rather than an ESQ on purpose: <c>SysSchema</c> carries restricted NUI security,
		/// and a name lookup that silently returns nothing because of permissions would be indistinguishable from a
		/// schema that does not exist.
		/// </remarks>
		private List<SchemaLayerInfo> FindSchemaLayersInternal(string schemaName, string packageName,
			string managerName){
			List<SchemaLayerInfo> layers = new List<SchemaLayerInfo>();
			Select select = new Select(_userConnection)
				.Column("s", "Id")
				.Column("s", "UId")
				.Column("s", "Name")
				.Column("s", "Caption")
				.Column("s", "ManagerName")
				.Column("p", "Name").As("PackageName")
				.Column("p", "UId").As("PackageUId")
				.From("SysSchema").As("s")
				.InnerJoin("SysPackage").As("p").On("p", "Id").IsEqual("s", "SysPackageId")
				.Where("s", "Name").IsEqual(Column.Parameter(schemaName)) as Select;
			if (!string.IsNullOrWhiteSpace(packageName)) {
				select = select.And("p", "Name").IsEqual(Column.Parameter(packageName.Trim())) as Select;
			}
			if (!string.IsNullOrWhiteSpace(managerName)) {
				select = select.And("s", "ManagerName").IsEqual(Column.Parameter(managerName.Trim())) as Select;
			}
			select = select.OrderByAsc("p", "Name") as Select;
			using (DBExecutor dbExecutor = _userConnection.EnsureDBConnection()) {
				using (IDataReader reader = select.ExecuteReader(dbExecutor)) {
					while (reader.Read()) {
						layers.Add(new SchemaLayerInfo {
							SchemaId = reader.GetColumnValue<Guid>("Id").ToString(),
							SchemaUId = reader.GetColumnValue<Guid>("UId").ToString(),
							SchemaName = reader.GetColumnValue<string>("Name"),
							Caption = reader.GetColumnValue<string>("Caption"),
							ManagerName = reader.GetColumnValue<string>("ManagerName"),
							PackageName = reader.GetColumnValue<string>("PackageName"),
							PackageUId = reader.GetColumnValue<Guid>("PackageUId").ToString()
						});
					}
				}
			}
			return layers;
		}

		/// <summary>
		/// Builds the error payload for a failed schema-transfer call.
		/// </summary>
		/// <remarks>
		/// Unwraps <see cref="TargetInvocationException"/> first. The platform importer/exporter is invoked by
		/// reflection (see <see cref="InvokeSchemaImporter"/>), and reflection replaces the real failure with the
		/// useless "Exception has been thrown by the target of an invocation." — which would hide exactly the
		/// message the caller needs, such as a locked target package.
		/// </remarks>
		private static ErrorInfo BuildErrorInfo(Exception exception){
			Exception root = exception;
			while (root is TargetInvocationException && root.InnerException != null) {
				root = root.InnerException;
			}
			return new ErrorInfo {
				Message = root.Message,
				StackTrace = root.StackTrace
			};
		}

		private static ErrorInfo BuildErrorInfo(string message) => new ErrorInfo { Message = message };

		// /rest/CreatioApiGateway/FindSchemaLayers
		/// <summary>
		/// Lists every package layer that carries a schema with the requested name.
		/// </summary>
		/// <param name="schemaName">Schema name to look up. Required.</param>
		/// <param name="managerName">Optional schema manager to narrow the lookup to, for example
		/// <c>AddonSchemaManager</c>.</param>
		/// <returns>The matching layers; an empty list when the schema does not exist.</returns>
		/// <remarks>
		/// Read-only. It exists so a caller can decide create-versus-replace, and detect a same-name schema owned by
		/// a different package, BEFORE an import writes anything.
		/// </remarks>
		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "FindSchemaLayers", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public FindSchemaLayersResponse FindSchemaLayers(string schemaName, string managerName = null){
			CheckCanManageSolution();
			FindSchemaLayersResponse response = new FindSchemaLayersResponse();
			try {
				if (string.IsNullOrWhiteSpace(schemaName)) {
					response.Success = false;
					response.ErrorInfo = BuildErrorInfo("schemaName is required");
					return response;
				}
				response.Layers = FindSchemaLayersInternal(schemaName.Trim(), null, managerName);
				response.Success = true;
			} catch (Exception exception) {
				_log.Error($"FindSchemaLayers failed for schema '{schemaName}'", exception);
				response.Success = false;
				response.ErrorInfo = BuildErrorInfo(exception);
			}
			return response;
		}

		// /rest/CreatioApiGateway/ExportSchema
		/// <summary>
		/// Exports a single schema using the platform schema exporter, returning the payload that
		/// <see cref="ImportSchema"/> consumes.
		/// </summary>
		/// <param name="schemaName">Schema name. Required.</param>
		/// <param name="packageName">Package that owns the layer to export. Required when the name matches more than
		/// one layer.</param>
		/// <param name="managerName">Optional schema manager, to narrow an ambiguous name further.</param>
		/// <returns>
		/// The exported payload and the identity of the layer it came from. When the name does not resolve to exactly
		/// one layer the call fails and returns the matching layers in <c>candidates</c> instead of guessing.
		/// </returns>
		/// <remarks>
		/// The platform exporter is type-agnostic — it serialises the schema metadata, its properties and its
		/// localizable resources for whichever manager owns the schema — so this endpoint covers every schema kind
		/// rather than one designer contract at a time.
		/// </remarks>
		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "ExportSchema", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public ExportSchemaResponse ExportSchema(string schemaName, string packageName = null,
			string managerName = null){
			CheckCanManageSolution();
			ExportSchemaResponse response = new ExportSchemaResponse();
			try {
				if (string.IsNullOrWhiteSpace(schemaName)) {
					response.Success = false;
					response.ErrorInfo = BuildErrorInfo("schemaName is required");
					return response;
				}
				List<SchemaLayerInfo> layers = FindSchemaLayersInternal(schemaName.Trim(), packageName, managerName);
				if (layers.Count == 0) {
					response.Success = false;
					response.ErrorInfo = BuildErrorInfo(
						$"Schema '{schemaName}' was not found in this environment" +
						(string.IsNullOrWhiteSpace(packageName) ? "." : $" in package '{packageName}'."));
					return response;
				}
				if (layers.Count > 1) {
					response.Success = false;
					response.Candidates = layers;
					response.ErrorInfo = BuildErrorInfo(
						$"Schema '{schemaName}' exists in {layers.Count} packages: " +
						string.Join(", ", layers.Select(layer => layer.PackageName).ToArray()) +
						". Specify the package to export.");
					return response;
				}
				SchemaLayerInfo schema = layers[0];
				response.SchemaData = InvokeSchemaExport(Guid.Parse(schema.SchemaId));
				response.Schema = schema;
				response.Success = true;
			} catch (Exception exception) {
				_log.Error($"ExportSchema failed for schema '{schemaName}'", exception);
				response.Success = false;
				response.ErrorInfo = BuildErrorInfo(exception);
			}
			return response;
		}

		// /rest/CreatioApiGateway/ImportSchema
		/// <summary>
		/// Imports a schema payload produced by <see cref="ExportSchema"/> into the named package.
		/// </summary>
		/// <param name="schemaData">Verbatim payload from <see cref="ExportSchema"/>. Required.</param>
		/// <param name="packageName">Target package name. Required, and must be an unlocked package of this
		/// environment.</param>
		/// <returns>The target package identity and the platform importer's own diagnostic string.</returns>
		/// <remarks>
		/// Writes through the platform schema importer, so schema properties, localizable resources, the
		/// extending-versus-standalone decision and the duplicate-name check are the platform's own — this endpoint
		/// does not reimplement them.
		/// </remarks>
		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "ImportSchema", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public ImportSchemaResponse ImportSchema(string schemaData, string packageName){
			CheckCanManageSolution();
			ImportSchemaResponse response = new ImportSchemaResponse();
			try {
				if (string.IsNullOrWhiteSpace(schemaData)) {
					response.Success = false;
					response.ErrorInfo = BuildErrorInfo("schemaData is required");
					return response;
				}
				if (string.IsNullOrWhiteSpace(packageName)) {
					response.Success = false;
					response.ErrorInfo = BuildErrorInfo("packageName is required");
					return response;
				}
				string targetPackageName = packageName.Trim();
				Guid packageUId = GetPackageUIdByName(targetPackageName);
				if (packageUId == Guid.Empty) {
					response.Success = false;
					response.ErrorInfo = BuildErrorInfo($"Package '{targetPackageName}' was not found in this environment.");
					return response;
				}
				response.ImportResult = InvokeSchemaImport(schemaData, packageUId);
				response.PackageName = targetPackageName;
				response.PackageUId = packageUId.ToString();
				response.Success = true;
			} catch (Exception exception) {
				_log.Error($"ImportSchema failed for package '{packageName}'", exception);
				response.Success = false;
				response.ErrorInfo = BuildErrorInfo(exception);
			}
			return response;
		}

		/// <summary>
		/// Calls the platform schema exporter.
		/// </summary>
		/// <param name="schemaId">Value of <c>SysSchema.Id</c> for the layer to export.</param>
		/// <returns>The platform export payload.</returns>
		/// <remarks>See <see cref="InvokeSchemaImporter"/> for why the call is late-bound and isolated.</remarks>
		[MethodImpl(MethodImplOptions.NoInlining)]
		private string InvokeSchemaExport(Guid schemaId) =>
			InvokeSchemaImporter(
				"ExportSchema", new object[] {schemaId, GetSystemUserConnection()},
				"ExportSchema", new object[] {schemaId});

		/// <summary>
		/// Calls the platform schema importer.
		/// </summary>
		/// <param name="schemaData">Payload previously produced by the exporter.</param>
		/// <param name="packageUId">UId of the package that will own the schema.</param>
		/// <returns>The platform importer's own diagnostic string.</returns>
		/// <remarks>See <see cref="InvokeSchemaImporter"/> for why the call is late-bound and isolated.</remarks>
		[MethodImpl(MethodImplOptions.NoInlining)]
		private string InvokeSchemaImport(string schemaData, Guid packageUId) =>
			InvokeSchemaImporter(
				"ImportSchemaToWorkspace", new object[] {schemaData, packageUId, _userConnection},
				"ImportSchema", new object[] {schemaData, packageUId});

		/// <summary>
		/// Calls the platform schema importer/exporter, trying the static entry point first and falling back to the
		/// <c>ISchemaImporter</c> instance one.
		/// </summary>
		/// <param name="staticMethodName">Name of the static <c>SchemaImporter</c> method to try first.</param>
		/// <param name="staticArguments">Arguments for the static call, in declaration order.</param>
		/// <param name="interfaceMethodName">Name of the <c>ISchemaImporter</c> method to fall back to.</param>
		/// <param name="interfaceArguments">Arguments for the interface call, in declaration order.</param>
		/// <returns>The value the platform method returned.</returns>
		/// <exception cref="InvalidOperationException">
		/// Thrown when neither entry point is available on the running core. The message lists what the class does
		/// expose under that name, so the mismatch is diagnosable from the response alone.
		/// </exception>
		/// <remarks>
		/// Late-bound on purpose, and BOTH shapes are genuinely needed. cliogate is compiled against one CreatioSDK
		/// but installed on environments running many different cores, and this API is not stable between them —
		/// verified, not assumed:
		/// <list type="bullet">
		/// <item><description>
		/// The 8.1 SDK exposes <c>SchemaImporter.ImportSchemaToWorkspace(string, Guid, UserConnection)</c> as a
		/// public static; a 10.1 stand has no public static of that name at all.
		/// </description></item>
		/// <item><description>
		/// On that 10.1 stand the operation is served only by the explicit implementation of
		/// <c>ISchemaImporter.ImportSchema(string, Guid)</c>, and <c>ISchemaImporter</c> is not accessible outside
		/// the core assembly — so it cannot be called early-bound either, and the interface type has to be recovered
		/// from <c>SchemaImporter</c>'s own interface list.
		/// </description></item>
		/// <item><description>
		/// <c>ExportSchema</c>, by contrast, is still a public static on both — hence static-first rather than
		/// interface-first.
		/// </description></item>
		/// </list>
		/// <para>
		/// A missing member is raised while the CALLING method is jitted, so an in-method try/catch never sees it and
		/// WCF answers with an opaque "Request Error". That is why each call site is a separate
		/// <see cref="MethodImplOptions.NoInlining"/> method rather than an inline call.
		/// </para>
		/// </remarks>
		[MethodImpl(MethodImplOptions.NoInlining)]
		private static string InvokeSchemaImporter(string staticMethodName, object[] staticArguments,
			string interfaceMethodName, object[] interfaceArguments){
			MethodInfo[] staticCandidates = typeof(SchemaImporter)
				.GetMethods(BindingFlags.Public | BindingFlags.Static)
				.Where(method => method.Name == staticMethodName)
				.ToArray();
			foreach (MethodInfo candidate in staticCandidates) {
				object[] callArguments = MatchArguments(candidate, staticArguments);
				if (callArguments != null) {
					return (string)candidate.Invoke(null, callArguments);
				}
			}
			Type importerInterface = typeof(SchemaImporter).GetInterfaces()
				.FirstOrDefault(contract => contract.Name == "ISchemaImporter");
			MethodInfo interfaceMethod = importerInterface?.GetMethod(interfaceMethodName,
				BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
			if (interfaceMethod != null) {
				object[] callArguments = MatchArguments(interfaceMethod, interfaceArguments);
				if (callArguments != null) {
					return (string)interfaceMethod.Invoke(ResolveSchemaImporter(importerInterface), callArguments);
				}
			}
			throw new InvalidOperationException(
				$"This Creatio version exposes neither a compatible static " +
				$"Terrasoft.Core.SchemaImporter.{staticMethodName} overload nor " +
				$"Terrasoft.Core.ISchemaImporter.{interfaceMethodName}. Static overloads found: " +
				$"{DescribeOverloads(staticMethodName, staticCandidates)}.");
		}

		/// <summary>
		/// Builds the platform schema importer instance whose interface method is invoked by reflection.
		/// </summary>
		/// <param name="importerInterface">The <c>ISchemaImporter</c> contract, recovered at runtime.</param>
		/// <returns>An importer instance.</returns>
		/// <exception cref="InvalidOperationException">
		/// Thrown when none of the resolution strategies produced an instance; the message carries what each one
		/// reported, because a failure here is a container-configuration difference between Creatio versions and is
		/// not otherwise diagnosable from the response.
		/// </exception>
		/// <remarks>
		/// Three strategies, in decreasing order of fidelity, because which one works depends on the target core:
		/// the container binding for the interface, the container binding for the concrete class, then a direct
		/// construction. All three go through the GENERIC <c>ClassFactory.Get&lt;T&gt;</c> where the container is
		/// used at all — the non-generic <c>ClassFactory.Get(Type)</c> routes through <c>GetInstance&lt;T&gt;</c>
		/// with <c>T</c> bound to <see cref="object"/> and fails with
		/// <c>Error creating an instance of the "System.Object" class</c>.
		/// </remarks>
		private static object ResolveSchemaImporter(Type importerInterface){
			List<string> failures = new List<string>();
			object instance = TryResolveFromClassFactory(importerInterface, failures)
				?? TryResolveFromClassFactory(typeof(SchemaImporter), failures)
				?? TryCreateDirectly(failures);
			if (instance == null) {
				throw new InvalidOperationException(
					"Could not obtain a Terrasoft.Core.SchemaImporter instance: " + string.Join("; ", failures.ToArray()));
			}
			return instance;
		}

		private static object TryResolveFromClassFactory(Type serviceType, List<string> failures){
			try {
				MethodInfo get = typeof(ClassFactory)
					.GetMethods(BindingFlags.Public | BindingFlags.Static)
					.First(method => method.Name == "Get"
						&& method.IsGenericMethodDefinition
						&& method.GetParameters().Length == 1
						&& method.GetParameters()[0].ParameterType == typeof(ConstructorArgument[]));
				return get.MakeGenericMethod(serviceType).Invoke(null, new object[] {new ConstructorArgument[0]});
			} catch (Exception exception) {
				Exception root = exception;
				while (root is TargetInvocationException && root.InnerException != null) {
					root = root.InnerException;
				}
				failures.Add($"ClassFactory.Get<{serviceType.Name}> -> {root.Message}");
				return null;
			}
		}

		private static object TryCreateDirectly(List<string> failures){
			try {
				return Activator.CreateInstance(typeof(SchemaImporter));
			} catch (Exception exception) {
				failures.Add($"new SchemaImporter() -> {exception.Message}");
				return null;
			}
		}

		private static string DescribeOverloads(string methodName, MethodInfo[] candidates) =>
			candidates.Length == 0
				? "none"
				: string.Join("; ", candidates
					.Select(method => methodName + "(" + string.Join(", ", method.GetParameters()
						.Select(parameter => parameter.ParameterType.Name).ToArray()) + ")")
					.ToArray());

		/// <summary>
		/// Binds the supplied arguments to a candidate method, dropping trailing arguments it does not declare.
		/// </summary>
		/// <param name="candidate">Method being considered.</param>
		/// <param name="arguments">Arguments available to pass, in declaration order.</param>
		/// <returns>The argument array to invoke with, or <c>null</c> when the method does not match.</returns>
		[SuppressMessage("Major Code Smell", "S1168:Empty arrays and collections should be returned instead of null",
			Justification = "null means 'this candidate does not match'; an empty array is the legitimate call "
				+ "argument list of a parameterless overload, so collapsing the two would invoke the wrong method.")]
		private static object[] MatchArguments(MethodInfo candidate, object[] arguments){
			ParameterInfo[] parameters = candidate.GetParameters();
			if (parameters.Length > arguments.Length) {
				return null;
			}
			for (int i = 0; i < parameters.Length; i++) {
				object argument = arguments[i];
				if (argument == null || !parameters[i].ParameterType.IsInstanceOfType(argument)) {
					return null;
				}
			}
			object[] callArguments = new object[parameters.Length];
			Array.Copy(arguments, callArguments, parameters.Length);
			return callArguments;
		}

		/// <summary>
		/// Returns the application's system user connection, which the platform schema exporter requires because it
		/// reads rows (localizable values, schema properties) the calling user may not be permitted to select.
		/// </summary>
		/// <remarks>
		/// <c>AppConnection.SystemUserConnection</c> is typed as the base <see cref="UserConnection"/>, so the cast is
		/// checked explicitly rather than done blindly: a wrong type here would otherwise surface as a
		/// <c>NullReferenceException</c> deep inside the exporter.
		/// </remarks>
		private SystemUserConnection GetSystemUserConnection(){
			SystemUserConnection systemUserConnection =
				_userConnection.AppConnection.SystemUserConnection as SystemUserConnection;
			if (systemUserConnection == null) {
				throw new InvalidOperationException(
					"The application does not expose a system user connection, which schema export requires.");
			}
			return systemUserConnection;
		}

		private Guid GetPackageUIdByName(string packageName){
			Select select = new Select(_userConnection)
				.Column("UId")
				.From("SysPackage").WithHints(new NoLockHint())
				.Where("Name").IsEqual(Column.Parameter(packageName)) as Select;
			return select.ExecuteScalar<Guid>();
		}

		#endregion

		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "GetPackages", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public string GetPackages(bool isCustomer = false){
			CheckCanManageSolution();
			List<Dictionary<string, string>> packageList = new List<Dictionary<string, string>>();
			EntitySchemaQuery esq = new EntitySchemaQuery(UserConnection.EntitySchemaManager, "SysPackage");
			esq.AddAllSchemaColumns();
			if (isCustomer) {
				string maintainerName = SysSettings.GetValue(UserConnection, "Maintainer", string.Empty);
				Guid customPackageUId = SysSettings.GetValue(UserConnection, "CustomPackageUId", Guid.Empty);
				IEntitySchemaQueryFilterItem maintainerNameFilter =
					esq.CreateFilterWithParameters(FilterComparisonType.Equal, "Maintainer", maintainerName);
				IEntitySchemaQueryFilterItem nameNotEqualCustomFilter =
					esq.CreateFilterWithParameters(FilterComparisonType.NotEqual, "UId", customPackageUId);
				IEntitySchemaQueryFilterItem installTypeFilter =
					esq.CreateFilterWithParameters(FilterComparisonType.Equal, "InstallType", 0);
				esq.Filters.Add(maintainerNameFilter);
				esq.Filters.Add(nameNotEqualCustomFilter);
				esq.Filters.Add(installTypeFilter);
			}
			EntityCollection packages = esq.GetEntityCollection(UserConnection);
			foreach (Entity p in packages) {
				Dictionary<string, string> package = new Dictionary<string, string> {
					["Name"] = p.PrimaryDisplayColumnValue,
					["UId"] = p.GetTypedColumnValue<string>("UId"),
					["Maintainer"] = p.GetTypedColumnValue<string>("Maintainer"),
					["Version"] = p.GetTypedColumnValue<string>("Version")
				};
				packageList.Add(package);
			}
			string json = JsonConvert.SerializeObject(packageList);
			return json;
		}

		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "LockPackages",
			BodyStyle = WebMessageBodyStyle.WrappedRequest, RequestFormat = WebMessageFormat.Json,
			ResponseFormat = WebMessageFormat.Json)]
		public bool LockPackages(string[] lockPackages = null){
			CheckCanManageSolution();
			_log.WarnFormat("Start LockPackages, packages: {0}", FormatPackageNamesForLog(lockPackages));
			string maintainerCode = SysSettings.GetValue(UserConnection, "Maintainer", "NonImplemented");
			if (lockPackages != null && lockPackages.Any()) {
				foreach (string lockPackage in lockPackages) {
					string packageNameForLog = FormatPackageNamesForLog(new[] {lockPackage});
					string originalMaintainer = GetPackageAttributeValue<string>("Maintainer", lockPackage);
					string[] description = SplitLockDescription(
						GetPackageAttributeValue<string>(DescriptionColumnName, lockPackage), splitName);
					string maintainer = description.Length > 1 ? description.Last() : originalMaintainer;
					Query query = new Update(UserConnection, "SysPackage")
						.Set("InstallType", Column.Parameter(1))
						.Set("Maintainer", Column.Parameter(maintainer))
						.Set(DescriptionColumnName, Column.Parameter(description[0]))
						.Where("Name").IsEqual(Column.Parameter(lockPackage));
					Update update = query as Update;
					update.BuildParametersAsValue = true;
					if (update.Execute() != 1) {
						_log.WarnFormat("Could not lock package {0}.", packageNameForLog);
						return false;
					}
				}
			} else {
				Query query = new Update(UserConnection, "SysPackage")
					.Set("InstallType", Column.Parameter(1, "Integer"))
					.Where("Maintainer").IsEqual(Column.Parameter(maintainerCode))
					.And("Name").IsNotEqual(Column.Parameter("Custom")) as Update;
				Update update = query as Update;
				update.Execute();
			}
			return true;
		}

		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "ResetSchemaChangeState",
			BodyStyle = WebMessageBodyStyle.WrappedRequest, RequestFormat = WebMessageFormat.Json,
			ResponseFormat = WebMessageFormat.Json)]
		public bool ResetSchemaChangeState(string packageName){
			CheckCanManageSolution();
			Update update = new Update(UserConnection, "SysSchema")
				.Set("IsChanged", Column.Parameter(false, "Boolean"))
				.Where("SysPackageId").In(new Select(UserConnection).Column("Id").From("SysPackage")
					.Where("SysPackage", "Name").IsEqual(Column.Parameter(packageName))) as Update;
			update.Execute();
			return true;
		}

		// /rest/CreatioApiGateway/SavePackageFileContent?packageName=CrtBase&filePath=descriptor12345.json&fileContent=123
		[OperationContract]
		[WebInvoke(Method = "POST", BodyStyle = WebMessageBodyStyle.WrappedRequest, RequestFormat = WebMessageFormat.Json,
			ResponseFormat = WebMessageFormat.Json)]
		public BaseResponse SavePackageFileContent(string packageName, string filePath, string fileContent){
			CheckCanManageSolution();

			PackageExplorer packageExplorer = new PackageExplorer(packageName);
			var result = packageExplorer.SaveFileContent(filePath, fileContent);
			return new BaseResponse {
				Success = result.isSuccess,
				ErrorInfo = new ErrorInfo() {
					Message = result.ex?.Message,
					StackTrace = result.ex?.StackTrace
				}
			};
		}

		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "UnlockPackages",
			BodyStyle = WebMessageBodyStyle.WrappedRequest, RequestFormat = WebMessageFormat.Json,
			ResponseFormat = WebMessageFormat.Json)]
		public bool UnlockPackages(string[] unlockPackages = null){
			CheckCanManageSolution();
			_log.WarnFormat("Start UnlockPackages, packages: {0}", FormatPackageNamesForLog(unlockPackages));
			string maintainerCode = SysSettings.GetValue(UserConnection, "Maintainer", "NonImplemented");
			_log.WarnFormat($"Maintainer code: {maintainerCode}");
			if (unlockPackages != null && unlockPackages.Any()) {
				foreach (string unlockPackage in unlockPackages) {
					string packageNameForLog = FormatPackageNamesForLog(new[] {unlockPackage});
					string originalMaintainer = GetPackageAttributeValue<string>("Maintainer", unlockPackage);
					string description = BuildUnlockDescription(
						GetPackageAttributeValue<string>(DescriptionColumnName, unlockPackage), originalMaintainer, splitName);
					Query query = new Update(UserConnection, "SysPackage")
						.Set("InstallType", Column.Parameter(0))
						.Set("Maintainer", Column.Parameter(maintainerCode))
						.Set(DescriptionColumnName, Column.Parameter(description))
						.Where("Name").IsEqual(Column.Parameter(unlockPackage));
					Update update = query as Update;
					update.BuildParametersAsValue = true;
					int isSuccess = update.Execute();
					_log.WarnFormat(isSuccess == 1
						? $"Successfully unlocked {packageNameForLog} package"
						: $"Could not unlock {packageNameForLog} packages.");
					if (isSuccess != 1) {
						return false;
					}
				}
			} else {
				_log.WarnFormat($"Start UnlockPackages, packages: all with maintainer code {maintainerCode}");
				Query query = new Update(UserConnection, "SysPackage")
					.Set("InstallType", Column.Parameter(0))
					.Where("Maintainer").IsEqual(Column.Parameter(maintainerCode));
				Update update = query as Update;
				int isSuccess = update.Execute();
				
				_log.WarnFormat(isSuccess == 1
					? $"Successfully unlocked package by maintainer code {maintainerCode}"
					: $"Could not unlock packages by maintainer code {maintainerCode}");
			}
			return true;
		}

		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "UpdateDBStructure", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public bool UpdateDBStructure(){
			CheckCanManageSolution();
			IEnumerable<Guid> invalidSchemas = GetEntitySchemasWithNeedUpdateStructure();
			return CreateInstallUtilities().SaveSchemaDBStructure(invalidSchemas, true);
		}

		[OperationContract]
		[WebInvoke(Method = "POST", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public BaseResponse UploadFile(Stream stream) {
			CheckCanManageSolution();
			HttpContext contextAccessor = HttpContextAccessor.GetInstance();
			HeaderCollection headers = contextAccessor.Request.Headers;
			const string fileNameHeader = "X-File-Name";
			const string packageNameHeader = "X-Package-Name";
			if (!headers.AllKeys.Contains(fileNameHeader)) {
				return new BaseResponse {
					Success = false,
					ErrorInfo = new ErrorInfo() {
						Message = $"Error: {fileNameHeader} header missing",
					}
				};
			}
			if (!headers.AllKeys.Contains(packageNameHeader)) {
				return new BaseResponse {
					Success = false,
					ErrorInfo = new ErrorInfo() {
						Message = $"Error: {packageNameHeader} header missing",
					}
				};
			}
			string filename = headers[fileNameHeader];
			string packageName = headers[packageNameHeader];

			PackageExplorer packageExplorer = new PackageExplorer(packageName);
			packageExplorer.SaveFileContent(filename, stream);

			return new BaseResponse {
				Success = true
			};
		}

		[OperationContract]
		[WebInvoke(Method = "POST", BodyStyle = WebMessageBodyStyle.Bare, ResponseFormat = WebMessageFormat.Json)]
		public string BackupStaticFiles() {
			CheckCanManageSolution();
			HttpContext contextAccessor = HttpContextAccessor.GetInstance();
			HeaderCollection headers = contextAccessor.Request.Headers;
			const string folderNameHeader = "X-Folder-Name";
			const string backupNameHeader = "X-Backup-Name";
			if (!headers.AllKeys.Contains(folderNameHeader)) {
				return $"Error: {folderNameHeader} header missing";
			}
			bool restoreFlag = headers.AllKeys.Contains(backupNameHeader);
			string folderName = headers[folderNameHeader];
			var staticContentExplorer = new StaticContentExplorer();
			if (restoreFlag) {
				string backupName = headers[backupNameHeader];
				return staticContentExplorer.RestoreStaticContent(folderName, backupName) ? backupName : null;
			}

			return staticContentExplorer.BackupStaticContent(folderName);
		}

		[OperationContract]
		[WebInvoke(Method = "POST", BodyStyle = WebMessageBodyStyle.Bare, ResponseFormat = WebMessageFormat.Json)]
		public BaseResponse UploadStaticFile(Stream stream) {
			CheckCanManageSolution();
			HttpContext contextAccessor = HttpContextAccessor.GetInstance();
			HeaderCollection headers = contextAccessor.Request.Headers;
			const string fileNameHeader = "X-File-Name";
			const string folderNameHeader = "X-Folder-Name";
			if (!headers.AllKeys.Contains(fileNameHeader)) {
				return new BaseResponse {
					Success = false,
					ErrorInfo = new ErrorInfo() {
						Message = $"Error: {fileNameHeader} header missing",
					}
				};
			}
			if (!headers.AllKeys.Contains(folderNameHeader)) {
				return new BaseResponse {
					Success = false,
					ErrorInfo = new ErrorInfo() {
						Message = $"Error: {folderNameHeader} header missing",
					}
				};
			}
			string fileName = headers[fileNameHeader];
			string folderName = headers[folderNameHeader];
			var response = new BaseResponse();
			using (var memoryStream = new MemoryStream()) {
				stream.CopyTo(memoryStream);
				memoryStream.Position = 0;
				using (var gzipStream = new GZipStream(memoryStream, CompressionMode.Decompress))
				using (var decompressedStream = new MemoryStream()) {
					gzipStream.CopyTo(decompressedStream);
					decompressedStream.Position = 0;
					var staticContentExplorer = new StaticContentExplorer();
					var saveResult = staticContentExplorer.SaveStaticContent(decompressedStream, folderName, fileName);
					response.Success = saveResult.isSuccess;
					if (saveResult.ex != null) {
						response.ErrorInfo = new ErrorInfo() {
							Message = saveResult.ex.Message,
						};
					}
				}
			}
			return response;
		}

		// 200: http://localhost:40020/rest/CreatioApiGateway/DownloadFile
		// 404: http://localhost:40020/rest/CreatioApiGateway/DownloadFile
		[OperationContract]
		[WebInvoke(Method = "POST", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public void DownloadFile(string packageName, string dllName){
			CheckCanManageSolution();
			PackageExplorer packageExplorer = new PackageExplorer(packageName);
			bool isNetCore = !HttpContext.Request.BaseUrl.EndsWith("/0");
			byte[] bytes = packageExplorer.GetBinaryFileContent(dllName, isNetCore);
			
			AssignFileResponseContent(bytes.Length, dllName);
			if(bytes.Length == 0) {
				SetReturnStatusCode(HttpStatusCode.NotFound);
			}
			SetReturnStatusCode(HttpStatusCode.OK);
			HttpContext.Current.Response.OutputStream.Write(bytes, 0, bytes.Length);
		}
		
		
		[OperationContract]
		[WebInvoke(Method = "POST", BodyStyle = WebMessageBodyStyle.WrappedRequest,
			RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public BaseResponse DeleteFile(string packageName, string filePath){
			CheckCanManageSolution();
			PackageExplorer packageExplorer = new PackageExplorer(packageName);
			(bool isSuccess, Exception ex) = packageExplorer.DeleteFile(filePath);
			
			if(!isSuccess) {
				return new BaseResponse {
					Success = isSuccess,
					ErrorInfo = {
						Message = ex.Message,
						StackTrace = ex.StackTrace
					}
				};
			}
			return new BaseResponse {
				Success = true
			};
			
		}

		// /rest/CreatioApiGateway/SendEventToUI
		[OperationContract]
		[WebInvoke(Method = "POST", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public void SendEventToUI(EventModel eventModel) {
			CheckCanManageSolution();
			var liveLogger = new LiveLogger(new WebSocket()); // Instantiate LiveLogger with WebSocket
			liveLogger.Log(eventModel.Content); // Use LiveLogger to log the event content
		}
		
		
		// /rest/CreatioApiGateway/GetApplicationIdByName?appName=ttt1
		[OperationContract]
		[WebInvoke(Method = "GET", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public string GetApplicationIdByName(string appName) {
			CheckCanManageSolution();
			EntitySchemaQuery esq = new EntitySchemaQuery(UserConnection.EntitySchemaManager, "SysInstalledApp");
			var columndId = esq.AddColumn("Id");
			
			esq.Filters.Add(
				esq.CreateFilterWithParameters(FilterComparisonType.Equal,"Name", appName));
			esq.Filters.Add(
				esq.CreateFilterWithParameters(FilterComparisonType.Equal, "Code", appName));
			esq.Filters.LogicalOperation = LogicalOperationStrict.Or;
			EntityCollection entities = esq.GetEntityCollection(UserConnection);
			if (entities.Count == 0) {
				return $"Application {appName} not found.";
			}
			if (entities.Count > 1) {
				return $"More then one application found.";
			}
			return entities[0].GetTypedColumnValue<string>(columndId.Name);
		}

		
		// /rest/CreatioApiGateway/GetSysInfo
		[OperationContract]
		[WebInvoke(Method = "GET", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
		public SysInfoResponse GetSysInfo(){
			if (!UserConnection.DBSecurityEngine.GetCanExecuteOperation("CanManageSolution")) {
				return new SysInfoResponse {
					Success = false,
					ErrorInfo = new ErrorInfo {
						Message = "You don't have permission for operation CanManageSolution"
					}
				};
			}

			EntitySchemaQuery esq = new EntitySchemaQuery(UserConnection.EntitySchemaManager, "SysPackage");
			esq.AddAllSchemaColumns();
			var packages = esq.GetEntityCollection(UserConnection);
			List<string> packageNames = new List<string>();
			foreach (Entity package in packages) {
				string name = package.GetTypedColumnValue<string>("Name");
				packageNames.Add(name);
			}
		
			bool isNetCore = !(Environment.Version.Major == 4); 
			
			var ver = Assembly.GetAssembly(typeof(UserConnection)).GetName().Version;
			ProductManager pm  = new ProductManager();
			SysInfoResponse sysInfoResponse = new SysInfoResponse {
				SysInfo = new CreatioPlatformInfo{
					Runtime = RuntimeInformation.FrameworkDescription,
					CoreVersion = ver.ToString(),
					DbEngineType = UserConnection.DBEngine.DBEngineType.ToString(),
					ProductName = pm.FindProductNameByPackages(packageNames, ver, isNetCore),
					IsNetCore = isNetCore,
				}
			};

			LicManager lm = UserConnection.AppConnection.LicManager;
			sysInfoResponse.SysInfo.LicenseInfo = new LicenseInfo {
				CustomerId = lm.CustomerId
			};
			IDataStore appData = UserConnection.AppConnection.SystemUserConnection.ApplicationData;
			if (appData.Keys.Contains("IsDemoMode")) {
				object isDemoMode = appData["IsDemoMode"];
				if (isDemoMode != null) {
					bool isBool = bool.TryParse(isDemoMode.ToString(), out bool demoMode);
					if (isBool) {
						sysInfoResponse.SysInfo.LicenseInfo.IsDemoMode = demoMode;
					}
				}
			}
			return sysInfoResponse;
		}

		// Toggles the FSM (file design mode) flag in the IIS host's Web.config and lets
		// IIS auto-recycle the AppPool to pick up the change. Enables clio on macOS/Linux
		// to remotely toggle FSM on a .NET Framework Creatio environment.
		[OperationContract]
		[WebInvoke(Method = "POST", UriTemplate = "SetFileDesignMode",
			BodyStyle = WebMessageBodyStyle.WrappedRequest, RequestFormat = WebMessageFormat.Json,
			ResponseFormat = WebMessageFormat.Json)]
		public SetFileDesignModeResponse SetFileDesignMode(bool isFileDesignMode) {
			CheckCanManageSolution();
			SetFileDesignModeResponse response = new SetFileDesignModeResponse();
			try {
				FileDesignModeLookup lookup = LocateFileDesignModeNode();
				response.WebConfigPath = lookup.WebConfigPath;
				response.SearchAttempts = string.Join("; ", lookup.Attempts.ToArray());

				if (lookup.FileDesignModeNode == null) {
					response.Success = false;
					response.ErrorInfo = new ErrorInfo {
						Message = "Could not locate <terrasoft>/<fileDesignMode enabled=\"...\"/> in any candidate Web.config. Tried: " + response.SearchAttempts
					};
					return response;
				}

				string fileDesignModeNewValue = isFileDesignMode ? "true" : "false";
				string useStaticFileContentNewValue = isFileDesignMode ? "false" : "true";

				response.PreviousFileDesignMode = lookup.FileDesignModeNode.Attributes["enabled"].Value;
				lookup.FileDesignModeNode.Attributes["enabled"].Value = fileDesignModeNewValue;
				response.NewFileDesignMode = fileDesignModeNewValue;

				UpdateUseStaticFileContent(lookup.Root, useStaticFileContentNewValue, response);

				File.WriteAllText(lookup.WebConfigPath, lookup.Document.OuterXml);
				response.Success = true;
				_log.WarnFormat("cliogate.SetFileDesignMode: fileDesignMode={0} → {1} ({2})",
					response.PreviousFileDesignMode, response.NewFileDesignMode, lookup.WebConfigPath);
			} catch (Exception ex) {
				response.Success = false;
				response.ErrorInfo = new ErrorInfo {
					Message = ex.Message,
					StackTrace = ex.StackTrace
				};
			}
			return response;
		}

		// Creatio on .NET Framework hosts the runtime under Terrasoft.WebApp, but the
		// fileDesignMode flag lives in the *root* site Web.config (the parent directory).
		// Try both, parent first.
		private static FileDesignModeLookup LocateFileDesignModeNode() {
			string baseDir = AppDomain.CurrentDomain.BaseDirectory;
			string[] candidatePaths = new[] {
				Path.Combine(baseDir, "..", "Web.config"),
				Path.Combine(baseDir, "Web.config")
			};

			FileDesignModeLookup result = new FileDesignModeLookup();
			foreach (string candidate in candidatePaths) {
				string resolved = Path.GetFullPath(candidate);
				result.Attempts.Add(resolved + " exists=" + File.Exists(resolved));
				if (!File.Exists(resolved)) {
					continue;
				}
				if (TryLoadFileDesignModeFromFile(resolved, result)) {
					return result;
				}
			}
			return result;
		}

		private static bool TryLoadFileDesignModeFromFile(string resolvedPath, FileDesignModeLookup result) {
			try {
				System.Xml.XmlDocument candidateDoc = new System.Xml.XmlDocument();
				candidateDoc.LoadXml(File.ReadAllText(resolvedPath));
				System.Xml.XmlNode candidateRoot = candidateDoc.DocumentElement;
				System.Xml.XmlNode candidateTerrasoft = candidateRoot?.SelectSingleNode("descendant::terrasoft");
				System.Xml.XmlNode candidateFdm = candidateTerrasoft?.SelectSingleNode("descendant::fileDesignMode");
				if (candidateFdm?.Attributes["enabled"] == null) {
					return false;
				}
				result.WebConfigPath = resolvedPath;
				result.Document = candidateDoc;
				result.Root = candidateRoot;
				result.FileDesignModeNode = candidateFdm;
				return true;
			} catch {
				return false;
			}
		}

		private static void UpdateUseStaticFileContent(System.Xml.XmlNode root, string newValue,
			SetFileDesignModeResponse response) {
			System.Xml.XmlNode appSettings = root.SelectSingleNode("descendant::appSettings");
			if (appSettings == null) {
				return;
			}
			foreach (System.Xml.XmlNode cNode in appSettings.ChildNodes) {
				if (cNode.Attributes?["key"]?.Value == "UseStaticFileContent") {
					response.PreviousUseStaticFileContent = cNode.Attributes["value"].Value;
					cNode.Attributes["value"].Value = newValue;
					response.NewUseStaticFileContent = newValue;
					return;
				}
			}
		}

		private sealed class FileDesignModeLookup
		{
			public string WebConfigPath { get; set; }
			public System.Xml.XmlDocument Document { get; set; }
			public System.Xml.XmlNode Root { get; set; }
			public System.Xml.XmlNode FileDesignModeNode { get; set; }
			public List<string> Attempts { get; } = new List<string>();
		}
		#endregion

	}

	[DataContract]
	public class SetFileDesignModeResponse : BaseResponse
	{
		[DataMember(Name = "WebConfigPath")]
		public string WebConfigPath { get; set; }

		[DataMember(Name = "SearchAttempts")]
		public string SearchAttempts { get; set; }

		[DataMember(Name = "PreviousFileDesignMode")]
		public string PreviousFileDesignMode { get; set; }

		[DataMember(Name = "NewFileDesignMode")]
		public string NewFileDesignMode { get; set; }

		[DataMember(Name = "PreviousUseStaticFileContent")]
		public string PreviousUseStaticFileContent { get; set; }

		[DataMember(Name = "NewUseStaticFileContent")]
		public string NewUseStaticFileContent { get; set; }
	}
	
	[DataContract]
	public class EventModel {

		[DataMember(Name = "Sender")]
		public string Sender { get; set; }
		
		[DataMember(Name = "Content")]
		public string Content { get; set; }

		[DataMember(Name = "CommandName")]
		public string CommandName { get; set; }

	}

	public class StaticContentExplorer : PackageExplorer
	{
		#region Fields: Private

		private readonly string _baseDir = AppDomain.CurrentDomain.BaseDirectory;
		private readonly ILog _log = LogManager.GetLogger(typeof(CreatioApiGateway));

		#endregion

		#region Constructors: Public

		public StaticContentExplorer() : base("cliogate") { }

		#endregion

		#region Methods: Private

		private string GetStaticContentDirectoryPath(string folderName) {
			CheckNameForDeniedSymbols(folderName);
			string staticContentPath = Path.Combine(_baseDir, folderName);
			if (!Directory.Exists(staticContentPath)) {
				Directory.CreateDirectory(staticContentPath);
			}
			return staticContentPath;
		}

		private string GetRelativePath(string basePath, string fullPath) {
			Uri baseUri = new Uri(AppendDirectorySeparatorChar(basePath));
			Uri fullUri = new Uri(fullPath);
			return Uri.UnescapeDataString(baseUri.MakeRelativeUri(fullUri).ToString().Replace('/', Path.DirectorySeparatorChar));
		}

		private string AppendDirectorySeparatorChar(string path) {
			if (!path.EndsWith(Path.DirectorySeparatorChar.ToString())) {
				return path + Path.DirectorySeparatorChar;
			}
			return path;
		}

		private void ExtractFilesWithOverwrite(string archivePath, string extractPath) {
			string extractRoot = Path.GetFullPath(AppendDirectorySeparatorChar(extractPath));
			using (ZipArchive archive = ZipFile.OpenRead(archivePath)) {
				foreach (var entry in archive.Entries) {
					if (string.IsNullOrEmpty(entry.Name)) {
						continue;
					}

					string destinationPath = Path.GetFullPath(Path.Combine(extractRoot, entry.FullName));
					if (!destinationPath.StartsWith(extractRoot, StringComparison.Ordinal)) {
						throw new IOException(string.Format("Blocked path-traversal archive entry: {0}", entry.FullName));
					}
					Directory.CreateDirectory(Path.GetDirectoryName(destinationPath));
					using (var entryStream = entry.Open())
					using (var destinationStream = new FileStream(destinationPath, FileMode.Create, FileAccess.Write)) {
						entryStream.CopyTo(destinationStream);
					}
				}
			}
		}

		#endregion

		#region Methods: Public

		public string BackupStaticContent(string folderName) {
			string directoryPath = GetStaticContentDirectoryPath(folderName);
			string backupDir = Path.Combine(directoryPath, "Backups");
			if (!Directory.Exists(backupDir)) {
				Directory.CreateDirectory(backupDir);
			}

			var oldBackups = Directory.GetFiles(backupDir, "backup_*.zip");
			foreach (var backup in oldBackups) {
				try {
					File.Delete(backup);
				} catch (Exception ex) {
					_log.WarnFormat("Failed to delete old backup: {0}. Error: {1}", backup, ex.Message);
				}
			}

			var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
			var backupName = $"backup_{timestamp}.zip";
			var backupPath = Path.Combine(backupDir, backupName);
			using (var archive = ZipFile.Open(backupPath, ZipArchiveMode.Create)) {
				foreach (var file in Directory.EnumerateFiles(directoryPath, "*", SearchOption.AllDirectories)) {
					if (file.StartsWith(backupDir, StringComparison.OrdinalIgnoreCase)) {
						continue;
					}
					string entryName = GetRelativePath(directoryPath, file);
					archive.CreateEntryFromFile(file, entryName, CompressionLevel.Optimal);
				}
			}

			return backupName;
		}

		public bool RestoreStaticContent(string folderName, string backupName) {
			CheckNameForDeniedSymbols(backupName);
			string directoryPath = GetStaticContentDirectoryPath(folderName);
			string backupDir = Path.Combine(directoryPath, "Backups");
			if (!Directory.Exists(backupDir)) {
				_log.Warn($"Restore failed: backup folder not found {backupDir}");
				return false;
			}

			string fullPath = Path.Combine(backupDir, backupName);
			if (!File.Exists(fullPath)) {
				_log.Warn($"Restore failed: backup file not found {fullPath}");
				return false;
			}

			foreach (var file in Directory.GetFiles(directoryPath)) {
				try {
					File.Delete(file);
				} catch (Exception ex) {
					_log.WarnFormat("Failed to delete file during restore: {0}. Error: {1}", file, ex.Message);
				}
			}

			foreach (var dir in Directory.GetDirectories(directoryPath)) {
				if (!Path.GetFileName(dir).Equals("Backups", StringComparison.OrdinalIgnoreCase)) {
					Directory.Delete(dir, recursive: true);
				}
			}

			ExtractFilesWithOverwrite(fullPath, directoryPath);
			return true;
		}

		public (bool isSuccess, Exception ex) SaveStaticContent(Stream fileContent, string folderName, string fileName) {
			CheckNameForDeniedSymbols(fileName);
			string fullPath = Path.Combine(GetStaticContentDirectoryPath(folderName), fileName);
			using (var destinationStream = new FileStream(fullPath, FileMode.Create, FileAccess.Write, FileShare.None)) {
				fileContent.CopyTo(destinationStream);
			}
			string extension = Path.GetExtension(fullPath);
			if (!extension.Equals(".zip", StringComparison.OrdinalIgnoreCase)) {
				return (true, null);
			}

			string directoryPath = Path.GetDirectoryName(fullPath);
			try {
				ExtractFilesWithOverwrite(fullPath, directoryPath);
				if (File.Exists(fullPath)) {
					File.Delete(fullPath);
				}
				return (true, null);
			} catch (Exception ex) {
				return (false, ex);
			}
		}

		#endregion
	}

	public class PackageExplorer
	{

		#region Fields: Private

		private readonly string _packageName;
		private readonly string _baseDir = AppDomain.CurrentDomain.BaseDirectory;
		private readonly ILog _log = LogManager.GetLogger(typeof(CreatioApiGateway));

		#endregion

		#region Constructors: Public

		public PackageExplorer(string packageName){
			CheckNameForDeniedSymbols(packageName);
			_packageName = packageName;
		}

		#endregion

		#region Methods: Private

		private string PackageDirectoryPath(){
			return Path.Combine(_baseDir, "Terrasoft.Configuration", "Pkg", _packageName, "Files");
		}

		
		private string PackageBinDirectoryPath()=> Path.Combine(PackageDirectoryPath(), "Bin");
		
		private bool IsPackageUnlocked(string packageName){
			var userConnection = ClassFactory.Get<UserConnection>();
			string maintainerCode = SysSettings.GetValue(userConnection, "Maintainer", "NonImplemented");
			Select select = new Select(userConnection)
				.From("SysPackage").WithHints(new NoLockHint())
				.Column(Func.Count("Id")).As("Count")
				.Where("Name").IsEqual(Column.Parameter(packageName)) 
				.And("InstallType").IsEqual(Column.Parameter(0))
				.And("Maintainer").IsEqual(Column.Parameter(maintainerCode))
				as Select;
			return select.ExecuteScalar<int>() == 1;
		}

		#endregion

		#region Methods: Protected

		protected void CheckNameForDeniedSymbols(string name) {
			string[] invalidArgs = {
				"%2e%2e%2f", "%2e%2e/", "..%2f", "%2e%2e%5c", "2e%2e\\", "..%5c",
				"%252e%252e%255c", "..%255c", "../", "..\\"
			};
			foreach (string invalidArg in invalidArgs) {
				if (name.Contains(invalidArg)) {
					throw new Exception("Invalid character");
				}
			}
		}

		#endregion

		#region Methods: Public

		public byte[] GetBinaryFileContent(string dllName, bool isNetCore){
			try {
				CheckNameForDeniedSymbols(dllName);
				return isNetCore  
					? File.ReadAllBytes(Path.Combine(PackageBinDirectoryPath(), "netstandard", dllName))
					: File.ReadAllBytes(Path.Combine(PackageBinDirectoryPath(), dllName));
			}catch(Exception ex) {
				_log.Error($"Error while reading file {dllName} from package {_packageName}", ex);
				return Array.Empty<byte>();
			}
		}
		
		public string GetPackageFileContent(string filePath){
			CheckNameForDeniedSymbols(filePath);
			return File.ReadAllText(Path.Combine(PackageDirectoryPath(), filePath));
		}

		public IEnumerable<string> GetPackageFilesDirectoryContent() =>
			Directory
				.GetFiles(PackageDirectoryPath(), "*.*", SearchOption.AllDirectories)
				.Select(f => f.Replace(PackageDirectoryPath(), string.Empty));

		public (bool isSuccess, Exception ex) SaveFileContent(string filePath, string fileContent){
			CheckNameForDeniedSymbols(filePath);
			if(!IsPackageUnlocked(_packageName)) {
				return (false, new Exception("Cannot save file in a locked package"));
			}
			string fullPath = Path.Combine(PackageDirectoryPath(), filePath);
			string directoryPath = Path.GetDirectoryName(fullPath);
			if (!Directory.Exists(directoryPath)) {
				Directory.CreateDirectory(directoryPath);
			}
			File.WriteAllText(fullPath, fileContent);
			return (true, null);
		}
		public (bool isSuccess, Exception ex) SaveFileContent(string filePath, Stream fileContent){
			CheckNameForDeniedSymbols(filePath);
			if(!IsPackageUnlocked(_packageName)) {
				return (false, new Exception("Cannot save file in a locked package"));
			}
			string fullPath = Path.Combine(PackageDirectoryPath(), filePath);
			string directoryPath = Path.GetDirectoryName(fullPath);
			if (!Directory.Exists(directoryPath)) {
				Directory.CreateDirectory(directoryPath);
			}
			File.WriteAllBytes(fullPath, fileContent.GetAllBytes());
			return (true, null);
		}

		#endregion

		public (bool isSuccess, Exception ex) DeleteFile(string filePath){
			CheckNameForDeniedSymbols(filePath);
			if(!IsPackageUnlocked(_packageName)) {
				return (false, new Exception("Cannot save file in a locked package"));
			}
			string fullPath = Path.Combine(PackageDirectoryPath(), filePath);
			string directoryPath = Path.GetDirectoryName(fullPath);
			if (!Directory.Exists(directoryPath)) {
				return (false, new DirectoryNotFoundException(directoryPath));
			}
			try {
				File.Delete(fullPath);
				return (true, null);
			} catch (Exception ex) {
				return (false, ex);
			}
		}

	}

	#endregion
}
