using System;
using System.Collections.Generic;
using Clio.Command.ChainItems;
using Clio.Common;
using Clio.Package;
using CommandLine;
using ErrorOr;
using Microsoft.Extensions.DependencyInjection;

namespace Clio.Command;

#region Class: AddPackageOptions

[Verb("add-package", Aliases = ["ap"],
	HelpText = "Add a package; --as-app also creates a localization schema and injectable resolver")]
public class AddPackageOptions : EnvironmentOptions{
	/// <summary>
	/// Package name to create.
	/// </summary>

	[Value(0, MetaName = "Name", Required = true,
		HelpText = "Package name, 1 to 70 characters, starting with a letter or non-lone underscore and containing only letters, digits, and underscores")]
	public string Name { get; set; }

	/// <summary>
	/// Creates an application descriptor for the package when requested.
	/// </summary>
	[Option('a', "as-app", Required = false,
		HelpText = "Create application package with localization schema and injectable resolver")]
	public bool AsApp { get; set; }

	[Option("asApp", Required = false, Hidden = true, HelpText = "Alias for --as-app")]
	public bool AsAppAlias {
		get => AsApp;
		set { if (value) AsApp = value; }
	}
	
	/// <summary>
	/// Prefix applied to schema names generated by <see cref="AsApp"/>.
	/// </summary>
	/// <remarks>
	/// Omitted, the prefix comes from the target environment's <c>SchemaNamePrefix</c> system setting.
	/// Supplied, it wins and no Creatio request is made; an empty value generates without a prefix.
	/// </remarks>
	[Option("schema-name-prefix", Required = false,
		HelpText = "Prefix for schemas generated by --as-app; omit to read SchemaNamePrefix from the environment")]
	public string SchemaNamePrefix { get; set; }

	/// <summary>
	/// Path to a Creatio build archive or extracted directory used by the follow-up download flow.
	/// </summary>
	[Option('b', "build", Required = false, 
		HelpText = "Path to Creatio zip file or extracted directory to get configuration from")]
	public string BuildZipPath { get; set; }

	/// <summary>
	/// Explicit workspace root path supplied by MCP callers.
	/// </summary>
	internal string WorkspacePath { get; set; }

	internal override bool RequiredEnvironment => false;
}

#endregion

#region Class: AddPackageCommand

public class AddPackageCommand(IPackageCreator packageCreator, ILogger logger, IFollowUpChain chain, 
	[FromKeyedServices(nameof(DconfChainItem))] IFollowupUpChainItem dconfChainItem) : Command<AddPackageOptions>{

	#region Methods: Public

	public override int Execute(AddPackageOptions options) {
		string originalCurrentDirectory = Environment.CurrentDirectory;
		try {
			if (!PackageCreator.IsValidPackageName(options.Name)) {
				logger.WriteError(PackageCreator.InvalidPackageNameMessage);
				return 1;
			}
			if (!IsRequestedPrefixValid(options.SchemaNamePrefix)) {
				logger.WriteError(SchemaNamePrefixResolver.InvalidPrefixMessage);
				return 1;
			}
			WarnWhenPrefixCannotApply(options);
			ApplyWorkspacePath(options);
			packageCreator.Create(options.Name, options.AsApp, options.SchemaNamePrefix);
			logger.WriteInfo("Done");
			return FollowUp(options);
		}
		finally {
			Environment.CurrentDirectory = originalCurrentDirectory;
		}
	}

	private int FollowUp(AddPackageOptions options) {

		IDictionary<string, object> ctx = chain.CreateContextFromOptions(options);
		ErrorOr<int> result = chain
							  .With(dconfChainItem)
							  .Execute(ctx);

		if (!result.IsError) {
			return result.Value;
		}
		foreach (ErrorOr.Error error in result.Errors) {
			logger.WriteError($"{error.Code} - {error.Description}");
		}
		return 1;
	}

	/// <summary>
	/// Validates a caller-supplied schema-name prefix. Omitted is valid, and so is a literally empty
	/// value - that is the documented way to ask for an unprefixed schema. A value that is nothing but
	/// whitespace is not: it is a typo, and honouring it silently would hand the caller exactly the
	/// unprefixed schema this option exists to prevent, with none of the three warnings.
	/// </summary>
	private static bool IsRequestedPrefixValid(string requestedPrefix) {
		if (requestedPrefix is null) {
			return true;
		}
		if (requestedPrefix.Length > 0 && requestedPrefix.Trim().Length == 0) {
			return false;
		}
		return SchemaNamePrefixResolver.IsValidPrefix(requestedPrefix.Trim());
	}

	private void WarnWhenPrefixCannotApply(AddPackageOptions options) {
		// Only --as-app generates a schema, so a prefix passed without it is consumed by nothing. Saying
		// so is the difference between "clio ignored my flag" and a silent no-op the caller never notices.
		if (options.SchemaNamePrefix is not null && !options.AsApp) {
			logger.WriteWarning(
				"--schema-name-prefix has no effect without --as-app: no schema is generated for a "
				+ "package that is not an application package.");
		}
	}

	private static void ApplyWorkspacePath(AddPackageOptions options) {
		if (string.IsNullOrWhiteSpace(options.WorkspacePath)) {
			return;
		}
		Environment.CurrentDirectory = options.WorkspacePath;
	}

	#endregion
}

#endregion
