using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using ModelContextProtocol.Server;

namespace Clio.Command.McpServer.Prompts.ProcessDesigner;

/// <summary>
/// Prompt helpers for editing an existing business process on a Creatio environment through MCP.
/// </summary>
[McpServerPromptType, Description("Prompts to edit an existing business process by applying operations")]
public static class ModifyBusinessProcessPrompt {

	/// <summary>
	/// Builds a prompt that edits an existing process by applying a list of operations.
	/// </summary>
	[McpServerPrompt(Name = "modify-business-process"),
	 Description("Prompt to edit an existing business process by applying a list of operations")]
	public static string PromptByProcess(
		[Required] [Description("The name of the target environment")]
		string environmentName,
		[Required] [Description("Process code (schema Name) or UId to edit")]
		string process) =>
		$"""
		 Edit the existing business process `{process}` on Creatio environment `{environmentName}` with the
		 `modify-business-process` tool. Steps: (1) call `describe-business-process` to inspect the current elements
		 and their names; (2) read `get-guidance name=process-modeling` for the operation and field contract;
		 (3) supply a JSON `operations` array (applied in order) — each item has an `op`: `addElement`,
		 `removeElement`, `addFlow`, `removeFlow`, `addParameter`, `addMapping`, `setParameter`, `removeParameter`,
		 `setFilter`, `clearFilter`, `setSignal`, `setElement`, `setConnections`, or `clearConnections`
		 — plus that op's arguments (the element / parameter / mapping / filter / signal shapes match a build;
		 `setParameter` updates a parameter in place, `removeParameter` is dependency-checked, `setFilter`/`clearFilter`
		 set or remove a `signalStart`'s record filter, `setSignal` reconfigures a `signalStart`'s record trigger
		 and its tracked-change `changedColumns` in place, and `setElement` changes element-level fields in place —
		 `useBackgroundMode` on any element kind, a `sendEmail` element's `email` block, where the fields you
		 pass (`mode`, `sender`, `subject`, `body`, `importance`, `ignoreErrors`, `performer`) replace the current
		 value but `to`/`cc`/`bcc` recipients match-or-append (an address the line already carries is a no-op, a new one is appended), and a `performTask` element's `performer` block
		 (`type:user|manager|role` plus `contact?`/`role?`/`showPage?` — WHO performs the task; `role` is the honest
		 "assign to a team": the created Activity carries the role in its own OwnerRole column with an EMPTY
		 owner, so never fake a team by writing a role id into the OwnerId parameter — that id is refused as
		 referencing no Contact record; the retired CallUserTask is refused by name because its runtime ignores
		 the assignment); `setConnections` binds the "Connected to" links of the
		 Activity an element creates and is an UPSERT keyed on `column`, so columns you do not list are left alone,
		 and `clearConnections` unbinds them). An `addMapping` with a `value` on a Lookup parameter takes a bare
		 non-empty record Guid (the route ships from CrtProcessBuilder 1.3.1.1, and this clio additionally
		 refuses any environment older than the version it bundles — up front, via the package-convergence
		 message — while an older clio surfaces the old package's `[#Lookup…#]`-macro rejection; either refusal
		 means the environment's package is behind, so update it rather than concluding the parameter is
		 unsettable). Any failed operation aborts the whole edit
		 (nothing is saved). Example — switch a process to start on record save: `removeElement` the start event,
		 `addElement` a `signalStart`, then `addFlow` from it to the first task. Confirm destructive removals
		 (`removeElement` / `removeFlow` / `removeParameter` / `clearConnections`) with the user before proceeding.
		 A SUCCESSFUL edit can still report caveats, and they arrive as `message-type: "Warning"` entries in
		 `execution-log-messages` — there is no separate `warnings` field on the response, so looking for one and
		 finding nothing is not evidence there were none. Read them: a connection bound to a column with no
		 connection-registry row is written at run time yet invisible to the record page's connections detail (and
		 normally to the designer), a `[#SysSettings...#]` expression is accepted unchecked, and a cleared binding is
		 reported only there because it disappears from `describe-business-process` afterwards. `setConnections` is
		 supported on six user tasks only — `performTask`, `EmailTemplateUserTask`, `UserQuestionUserTask`,
		 `OpenEditPageUserTask`, `AutoGeneratedPageUserTask`, `PreconfiguredPageUserTask` — and any other element is
		 refused with the supported list, so check `writesConnectionsAtRuntime` in `describe-business-process` first:
		 `false` and `null` both mean `setConnections` will be refused there.
		 To link an Activity to the CURRENT USER, send `expression` with one of exactly three system variables,
		 chosen by the target column's entity — `[#SysVariable.CurrentUserContact#]`,
		 `[#SysVariable.CurrentUserAccount#]`, `[#SysVariable.CurrentUser#]`. That is the whole set, and system
		 variables cannot be looked up (they are neither an entity nor an entity schema). Spell them exactly: a
		 name outside the set is refused by a current `CrtProcessBuilder` and stored unchecked by an older one,
		 where it then breaks the process compile instead.
		 """;
}
