apiVersion: v1
kind: Service
metadata:
  name: redis-service-lb
  annotations:
    a8r.io/description: "This service exposes redis outside cluster, use port in ConnectionStrings.config"
  namespace: clio-infrastructure
  labels:
    app: clio-redis
spec:
  selector:
    app: clio-redis
  type: LoadBalancer 
  ports:
  - port: 6379
    targetPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-internal
  annotations:
    a8r.io/description: "This is cluster internal service, primarily used by email listener"
  namespace: clio-infrastructure
  labels:
    app: clio-redis
spec:
  selector:
    app: clio-redis
  type: ClusterIP 
  ports:
  - port: 6379
    targetPort: 6379