[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:creatio-webhost]
command=/usr/bin/dotnet /app/Terrasoft.WebHost.dll
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/creatio-webhost.log
stderr_logfile=/var/log/supervisor/creatio-webhost_err.log
