environment:
  url: https://production.creatio.com
  username: admin # or use OAuth token
  password: password # or use OAuth token
  clientid: "{client-id}"
  clientsecret: "{client-secret}"
  authappurl: https://production.creatio.com/0/ServiceModel/AuthService.svc/Login
  platformversion: "8.1.1"
  platformtype: "NET6" # "NET6" or "NETFramework"

apps:
  - name: CrtCustomer360
    version: "1.5.2"
    apphub: MyAppHub
  - name: CrtCaseManagment
    version: "1.0.2"
    apphub: CreatioMarketplace

syssettings:
  - name: SysSettings1
    value: Value1
  - name: SysSettings2
    value: Value2

features:
  - name: Feature1
    enabled: "true"
  - name: Feature2
    enabled: "false"

webservices:
  - name: WebService1
    url: "https://preprod.creatio.com/0/ServiceModel/EntityDataService.svc"
  - name: WebService2
    url: "https://preprod.creatio.com/0/ServiceModel/EntityDataService.svc"

packages:
  - name: Package1
    version: "1.0.1"
  - name: Package2
    version: "1.0.2"

apphubs:
  - name: MyAppHub
    path: "//tscrm.com/dfs-ts/MyAppHub"
  - name: CreatioMarketplace
    url: "https://marketplace.creatio.com/apps"

preflightactions:
  - name: PreflightAction1
    type: "Clio.Creatio.PreFlightActions.ExamplePreflightAction, Clio.Creatio.PreFlightActions"
  - name: PreflightAction2
    type: "Clio.Creatio.PreFlightActions.ExamplePreflightAction, Clio.Creatio.PreFlightActions"

postflightactions:
  - name: PostflightAction1
    type: "Clio.Creatio.PostFlightActions.ExamplePostflightAction, Clio.Creatio.PostFlightActions"
  - name: PostflightAction2
    type: "Clio.Creatio.PostFlightActions.ExamplePostflightAction, Clio.Creatio.PostFlightActions"