using System.IO;
using System.Linq;
using System.Xml.Linq;
using Clio;
using Clio.Command;
using Clio.Common;
using Clio.Project;
using FluentAssertions;
using NSubstitute;
using NUnit.Framework;

namespace Clio.Tests.Project;

[TestFixture]
[Category("Unit")]
[Property("Module", "Command")]
public class CreatioPkgProjectReferenceTests
{

	#region Setup/Teardown

	[SetUp]
	public void SetUp(){
		_workingDirectory = Path.Combine(TestContext.CurrentContext.TestDirectory,
			$"refproj-{TestContext.CurrentContext.Test.ID}");
		Directory.CreateDirectory(_workingDirectory);
	}

	[TearDown]
	public void TearDown(){
		if (Directory.Exists(_workingDirectory)) {
			Directory.Delete(_workingDirectory, true);
		}
	}

	#endregion

	#region Fields: Private

	private string _workingDirectory;

	#endregion

	#region Methods: Private

	private string CreateProject(string hintPath){
		string projectPath = Path.Combine(_workingDirectory, "TestPkg.csproj");
		File.WriteAllText(projectPath, $@"<?xml version=""1.0"" encoding=""utf-8""?>
<Project ToolsVersion=""15.0"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
  <ItemGroup>
    <Reference Include=""Terrasoft.Core"">
      <HintPath>{hintPath}</HintPath>
    </Reference>
    <None Include=""packages.config"" />
  </ItemGroup>
</Project>");
		return projectPath;
	}

	private static string ReadHintPath(string projectPath){
		XNamespace ns = "http://schemas.microsoft.com/developer/msbuild/2003";
		return XElement.Load(projectPath).Descendants(ns + "HintPath").First().Value;
	}

	#endregion

	[Test]
	[Description("Rebases references of a package generated by current clio, which uses the CreatioSDK nuget folder (issue 1280)")]
	public void RefToBin_RebasesCreatioSdkReferences(){
		// Arrange
		string projectPath = CreateProject(@"packages\CreatioSDK.7.15.2.501\lib\net40\Terrasoft.Core.dll");
		CreatioPkgProject sut = CreatioPkgProject.LoadFromFile(projectPath);

		// Act
		sut.RefToBin();
		sut.SaveChanges();

		// Assert
		sut.ChangedReferencesCount.Should().Be(1,
			because: "the package template ships CreatioSDK references and they must be recognized");
		ReadHintPath(projectPath).Should().Be(@"..\..\..\Bin\Terrasoft.Core.dll",
			because: "bin references point at the local Creatio Bin folder");
	}

	[Test]
	[Description("Still recognizes the pre-rename BpmonlineSDK reference style (issue 1280)")]
	public void RefToBin_RebasesLegacyBpmonlineSdkReferences(){
		// Arrange
		string projectPath = CreateProject(@"packages\BpmonlineSDK.7.13.0\lib\net40\Terrasoft.Core.dll");
		CreatioPkgProject sut = CreatioPkgProject.LoadFromFile(projectPath);

		// Act
		sut.RefToBin();
		sut.SaveChanges();

		// Assert
		sut.ChangedReferencesCount.Should().Be(1,
			because: "packages created by older clio versions must keep working");
		ReadHintPath(projectPath).Should().Be(@"..\..\..\Bin\Terrasoft.Core.dll",
			because: "bin references point at the local Creatio Bin folder");
	}

	[Test]
	[Description("Rewrites references whose HintPath uses forward slashes (issue 1280)")]
	public void RefToBin_RebasesReferencesWithForwardSlashes(){
		// Arrange
		string projectPath = CreateProject("packages/CreatioSDK.7.15.2.501/lib/net40/Terrasoft.Core.dll");
		CreatioPkgProject sut = CreatioPkgProject.LoadFromFile(projectPath);

		// Act
		sut.RefToBin();
		sut.SaveChanges();

		// Assert
		sut.ChangedReferencesCount.Should().Be(1,
			because: "MSBuild accepts either separator, and a csproj edited on macOS carries forward slashes");
		ReadHintPath(projectPath).Should().Be(@"..\..\..\Bin\Terrasoft.Core.dll",
			because: "bin references point at the local Creatio Bin folder");
	}

	[Test]
	[Description("Rewrites every reference when the project mixes both SDK folder names (issue 1280)")]
	public void RefToBin_RebasesMixedSdkStyles(){
		// Arrange
		string projectPath = Path.Combine(_workingDirectory, "TestPkg.csproj");
		File.WriteAllText(projectPath, @"<?xml version=""1.0"" encoding=""utf-8""?>
<Project ToolsVersion=""15.0"">
  <ItemGroup>
    <Reference Include=""Terrasoft.Core"">
      <HintPath>packages\CreatioSDK.7.15.2.501\lib\net40\Terrasoft.Core.dll</HintPath>
    </Reference>
    <Reference Include=""Terrasoft.Common"">
      <HintPath>packages\BpmonlineSDK.7.13.0\lib\net40\Terrasoft.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>");
		CreatioPkgProject sut = CreatioPkgProject.LoadFromFile(projectPath);

		// Act
		sut.RefToBin();

		// Assert
		sut.ChangedReferencesCount.Should().Be(2,
			because: "leaving half the references on the nuget folder is the silent breakage of issue 1280");
	}

	[Test]
	[Description("Reports success without changes when the project is already in the requested style (issue 1280)")]
	public void Execute_ReportsSuccess_When_ProjectIsAlreadyInRequestedStyle(){
		// Arrange
		string projectPath = CreateProject(@"..\..\..\Bin\Terrasoft.Core.dll");
		ICreatioPkgProjectCreator creator = Substitute.For<ICreatioPkgProjectCreator>();
		creator.CreateFromFile(projectPath).Returns(CreatioPkgProject.LoadFromFile(projectPath));
		ILogger logger = Substitute.For<ILogger>();
		ReferenceCommand command = new(creator, logger);

		// Act
		int actual = command.Execute(new ReferenceOptions {Path = projectPath, ReferenceType = "bin"});

		// Assert
		actual.Should().Be(0,
			because: "running ref-to twice, or on an already rebased project, is not a failure");
		File.ReadAllText(projectPath).Should().Contain("packages.config",
			because: "a run that changes nothing must not strip packages.config");
	}

	[Test]
	[Description("Reports an unrecognized reference style instead of silently changing nothing (issue 1280)")]
	public void Execute_ReportsFailure_When_NoReferenceWasChanged(){
		// Arrange
		string projectPath = CreateProject(@"some\unknown\layout\Terrasoft.Core.dll");
		ICreatioPkgProjectCreator creator = Substitute.For<ICreatioPkgProjectCreator>();
		creator.CreateFromFile(projectPath).Returns(CreatioPkgProject.LoadFromFile(projectPath));
		ILogger logger = Substitute.For<ILogger>();
		ReferenceCommand command = new(creator, logger);

		// Act
		int actual = command.Execute(new ReferenceOptions {Path = projectPath, ReferenceType = "bin"});

		// Assert
		actual.Should().Be(1,
			because: "changing nothing is a failure, not a success the user should act on");
		logger.Received(1).WriteError(Arg.Is<string>(m => m.Contains("Could not recognize the reference style")));
		File.ReadAllText(projectPath).Should().Contain("packages.config",
			because: "a failed rebase must not strip packages.config from the project");
	}

}
