using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Nodes;
using static Clio.Command.BusinessRules.BusinessRuleConstants;

namespace Clio.Command.BusinessRules;

/// <summary>
/// Stamps the stable identity of an existing persisted rule onto freshly converted replacement
/// metadata so an update stores a short diff instead of a full rule copy: the rule uId, the
/// single case and top-level condition-group uIds, and trigger uIds matched by (name, type) are
/// taken from the existing rule; caller-supplied block uIds are already stamped by the converter.
/// Autogenerated child rules of an apply-filter parent are re-anchored to the preserved rule uId.
/// </summary>
internal static class BusinessRuleIdentityGrafter {

	internal static IReadOnlyList<BusinessRuleMetadataDto> Graft(
		JsonObject existingRule,
		IReadOnlyList<BusinessRuleMetadataDto> generatedRules,
		bool? requestedEnabled) {
		ArgumentNullException.ThrowIfNull(existingRule);
		ArgumentNullException.ThrowIfNull(generatedRules);
		if (generatedRules.Count == 0) {
			throw new ArgumentException("At least one generated business rule is required.", nameof(generatedRules));
		}

		BusinessRuleMetadataDto parent = generatedRules[0];
		string generatedUId = parent.UId;
		string existingUId = GetString(existingRule, "uId")
			?? throw new InvalidOperationException("Existing business rule has no uId.");

		parent.UId = existingUId;
		parent.Enabled = requestedEnabled ?? GetBool(existingRule, "enabled", defaultValue: true);
		GraftCaseIdentity(existingRule, parent);
		GraftTriggerIdentity(existingRule, parent);
		ReanchorChildRules(generatedRules, generatedUId, existingUId);
		return generatedRules;
	}

	private static void GraftCaseIdentity(JsonObject existingRule, BusinessRuleMetadataDto parent) {
		if (parent.Cases.Count != 1
			|| existingRule["cases"] is not JsonArray existingCases
			|| existingCases.Count != 1
			|| existingCases[0] is not JsonObject existingCase) {
			return;
		}

		string? existingCaseUId = GetString(existingCase, "uId");
		if (!string.IsNullOrWhiteSpace(existingCaseUId)) {
			parent.Cases[0].UId = existingCaseUId;
		}

		if (parent.Cases[0].Condition is BusinessRuleGroupConditionMetadataDto generatedGroup
			&& existingCase["condition"] is JsonObject existingCondition
			&& string.Equals(GetString(existingCondition, "typeName"), BusinessRuleGroupConditionTypeName,
				StringComparison.Ordinal)) {
			string? existingGroupUId = GetString(existingCondition, "uId");
			if (!string.IsNullOrWhiteSpace(existingGroupUId)) {
				generatedGroup.UId = existingGroupUId;
			}
		}
	}

	private static void GraftTriggerIdentity(JsonObject existingRule, BusinessRuleMetadataDto parent) {
		if (existingRule["triggers"] is not JsonArray existingTriggers) {
			return;
		}

		// Creatio strips zero-valued properties when persisting addon metadata, so a change trigger
		// (ChangeAttributeValueTriggerType = 0) comes back without a "type" property at all —
		// default to 0, not a sentinel, or no change trigger would ever match.
		List<(string Name, int Type, string UId)> unconsumed = existingTriggers
			.OfType<JsonObject>()
			.Select(trigger => (
				Name: GetString(trigger, "name") ?? string.Empty,
				Type: GetInt(trigger, "type", ChangeAttributeValueTriggerType),
				UId: GetString(trigger, "uId") ?? string.Empty))
			.Where(trigger => !string.IsNullOrWhiteSpace(trigger.UId))
			.ToList();

		foreach (BusinessRuleTriggerMetadataDto generatedTrigger in parent.Triggers) {
			int matchIndex = unconsumed.FindIndex(candidate =>
				candidate.Type == generatedTrigger.Type
				&& string.Equals(candidate.Name, generatedTrigger.Name ?? string.Empty,
					StringComparison.OrdinalIgnoreCase));
			if (matchIndex < 0) {
				continue;
			}

			generatedTrigger.UId = unconsumed[matchIndex].UId;
			unconsumed.RemoveAt(matchIndex);
		}
	}

	/// <summary>
	/// Re-anchors regenerated apply-filter child rules from the converter's throwaway parent uId to
	/// the preserved existing uId. Child names and captions embed the parent uId
	/// (<c>Autogenerated_{uId}_…</c> / <c>ChildRule-{uId}-…</c>), so those embeds are rewritten too.
	/// </summary>
	private static void ReanchorChildRules(
		IReadOnlyList<BusinessRuleMetadataDto> generatedRules,
		string generatedParentUId,
		string existingParentUId) {
		foreach (BusinessRuleMetadataDto child in generatedRules.Skip(1)) {
			if (!string.Equals(child.ParentUId, generatedParentUId, StringComparison.OrdinalIgnoreCase)) {
				continue;
			}

			child.ParentUId = existingParentUId;
			child.Name = child.Name.Replace(generatedParentUId, existingParentUId, StringComparison.OrdinalIgnoreCase);
			if (!string.IsNullOrWhiteSpace(child.Caption)) {
				child.Caption = child.Caption.Replace(generatedParentUId, existingParentUId,
					StringComparison.OrdinalIgnoreCase);
			}
		}
	}

	private static string? GetString(JsonObject source, string propertyName) =>
		source[propertyName] is JsonValue value && value.TryGetValue(out string? text) ? text : null;

	private static bool GetBool(JsonObject source, string propertyName, bool defaultValue) =>
		source[propertyName] is JsonValue value && value.TryGetValue(out bool result) ? result : defaultValue;

	private static int GetInt(JsonObject source, string propertyName, int defaultValue) =>
		source[propertyName] is JsonValue value && value.TryGetValue(out int result) ? result : defaultValue;
}
