---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-data-pv
  labels:
    type: local
    app: clio-postgres
spec:
  storageClassName: clio-storage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/clio-infrastructure/postgres/data"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-backup-images-pv
  labels:
    type: local
    app: clio-postgres
spec:
  storageClassName: clio-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/clio-infrastructure/postgres/backup-images"