---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: clio-infrastructure
data:
  postgresql.conf: |-
    # Network
    # Listen on all network interfaces (required for Kubernetes service access)
    listen_addresses = '*'
    
    # Connection Settings
    max_connections = 100
    
    # Memory Settings (adjusted for 4Gi container limit)
    shared_buffers = 1GB
    work_mem = 64MB
    maintenance_work_mem = 512MB
    effective_cache_size = 3GB
    temp_buffers = 128MB
    
    # Parallelism
    max_worker_processes = 8
    max_parallel_workers_per_gather = 4
    max_parallel_maintenance_workers = 2
    max_parallel_workers = 8
    
    # Write Ahead Log (WAL)
    wal_level = minimal
    max_wal_senders = 0
    max_replication_slots = 0
    wal_compression = on
    max_wal_size = 4GB
    min_wal_size = 1GB
    checkpoint_timeout = 15min
    checkpoint_completion_target = 0.9
    full_page_writes = on
    
    # Query Planner
    seq_page_cost = 1.0
    random_page_cost = 1.1
    effective_io_concurrency = 200
    maintenance_io_concurrency = 200
    default_statistics_target = 200
    
    # JIT
    jit = off
    
    # Logging
    log_checkpoints = on
    log_min_duration_statement = 200ms
    log_lock_waits = on
    log_timezone = 'UTC'
    
    # Autovacuum
    autovacuum_vacuum_scale_factor = 0.1
    autovacuum_analyze_scale_factor = 0.05
    autovacuum_vacuum_cost_limit = 400
    autovacuum_vacuum_cost_delay = 2ms
    
    # Locale and Formatting
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
    
    # Shared Memory
    dynamic_shared_memory_type = posix
    
    # Authentication configuration file
    hba_file = '/etc/postgresql/pg_hba.conf'

  pg_hba.conf: |-
    # PostgreSQL Client Authentication Configuration File
    # ===================================================
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    
    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            scram-sha-256
    
    # IPv4 connections from within the cluster (pod network)
    host    all             all             10.0.0.0/8              scram-sha-256
    
    # IPv4 connections from any source (for LoadBalancer access)
    # WARNING: In production, restrict this to specific IP ranges
    host    all             all             0.0.0.0/0               scram-sha-256
    
    # IPv6 local connections:
    host    all             all             ::1/128                 scram-sha-256
    
    # IPv6 connections from any source
    host    all             all             ::/0                    scram-sha-256
    
    # Replication connections (currently disabled as wal_level = minimal)
    # local   replication     all                                   trust
    # host    replication     all             127.0.0.1/32          scram-sha-256
    # host    replication     all             ::1/128               scram-sha-256

  init-db.sql: |-
    -- Database initialization script
    -- This script runs once when the database is first created
    
    -- Grant necessary permissions to postgres user
    ALTER USER postgres WITH SUPERUSER CREATEDB CREATEROLE REPLICATION;
    
    -- Enable required extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_trgm";
    
    -- Set default privileges for future objects
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
    
    -- Log successful initialization
    DO $$
    BEGIN
        RAISE NOTICE 'Database initialization completed successfully';
    END $$;

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-data-pv
  labels:
    type: local
    app: clio-postgres
spec:
  storageClassName: clio-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/clio-infrastructure/postgres/data"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-backup-images-pv
  labels:
    type: local
    app: clio-postgres
spec:
  storageClassName: clio-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/clio-infrastructure/postgres/backup-images"