apiVersion: v1
kind: Service
metadata:
  name: postgres-service-lb
  namespace: clio-infrastructure
  labels:
    app: clio-postgres
spec:
    ports:
    - port: 5432
      targetPort: 5432
    type: LoadBalancer
    selector:
      app: clio-postgres


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-internal
  namespace: clio-infrastructure
  labels:
    app: clio-postgres
spec:
    ports:
    - port: 5432
      targetPort: 5432
    type: ClusterIP
    selector:
      app: clio-postgres
