### Protected Access
< set-request-base_url.js

POST {{base_url}}/0/DataService/json/SyncReply/InsertSysSettingRequest HTTP/1.1
Content-Type: application/json
BPMCSRF: {{BPMCSRF}}

{
  "id":"c7363e33-f8cc-4059-9761-a7c379088489",
  "name":"MySettingR",
  "code":"MySettingR",
  "description":"description test",
  "valueTypeName":"MaxSizeText",
  "isPersonal":true,
  "isCacheable":true
}
