using System.ComponentModel;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace Clio.Command.McpServer.Resources;

/// <summary>
/// Provides canonical AI-facing guidance for Freedom UI page modification through clio MCP. This is the
/// ENTRY guide of the page-modification family: it owns the mandatory pre-edit GATE checklist and the
/// canonical flow, then routes the detailed mechanics to four focused sub-guides
/// (<c>page-modification-overview</c>, <c>-field-contract</c>, <c>-containers</c>, <c>-components</c>),
/// each kept small so a single <c>get-guidance</c> response stays within the agent token limit.
/// </summary>
[McpServerResourceType]
public sealed class PageModificationGuidanceResource {
	private const string DocsScheme = "docs";
	private const string ResourcePath = "mcp/guides/page-modification";
	private const string ResourceUri = DocsScheme + "://" + ResourcePath;

	/// <summary>
	/// Canonical guidance article accessible by name through <c>get-guidance</c>.
	/// </summary>
	internal static readonly TextResourceContents Guide = new() {
		Uri = ResourceUri,
		MimeType = "text/plain",
		Text = """
		       clio MCP page modification guide

		       ENTRY guide for editing a Freedom UI page: run the pre-edit GATE checklist below, then read the ONE sub-guide matching your edit (each fits a single get-guidance response):
		       - save lifecycle (flow, replacing schema, write modes, conflicts, formatting) -> `page-modification-overview`
		       - insert a data-bound field (viewModelConfigDiff binding, label/resource rule, payload, diagnostics) -> `page-modification-field-contract`
		       - pick where a component goes (bundle.json, jq recipes, valid `parentName`) -> `page-modification-containers`
		       - compose a viewConfigDiff insert (button+handler, operation/type/name rules, reading get-component-info) -> `page-modification-components`

		       PRE-EDIT GUIDANCE CHECKLIST — MANDATORY before writing any body
		       STEP 0 — WEB, MOBILE, OR BOTH (before list-pages/get-page): web and mobile are SEPARATE page schemas (e.g., `<Entity>_FormPage`/`_ListPage` vs `<Entity>_MobileFormPage`/`_MobileListPage`) — editing one never affects its counterpart. Decide whether the requirement targets web, mobile, or both; if it does not say, default to web (mobile is an explicit opt-in). Then for every page it touches edit each targeted variant (mobile pass: read `mobile-page-modification` first).

		       MOBILE CHECK: If `get-page` returned `schema-type: "mobile"`, STOP — call `get-guidance` with name `mobile-page-modification` instead. Mobile pages use plain JSON (NOT AMD), draw from a separate component catalog (different list of components, same wrapped registry envelope and same `get-component-info` response shape — pass `schema-type: "mobile"` to query it), and must NOT contain handlers, validators, or converters. The rules below apply ONLY to web pages (schema-type: "web"). NOTE: even on mobile, a subset of the checklist below still applies (notably `page-schema-resources` and entity-level `business-rules`) — the mobile guide lists which items carry over.

		       GATE: if ANY row in the table below matches your change, you MUST call the listed guide before producing the body. Skipping a matching row is treated as a defect, not a shortcut.

		       | Requirement pattern | Call get-guidance with name | Why |
		       | --- | --- | --- |
		       | conditional visibility, editability, required state based on field values or conditional set and clear value. Also filtering of lookups, based on condition or valur from other field. If task contains setting a lookup, based on condition or based on value in other lookup field, use business rules. (e.g. "when Status=Closed hide field X"), OR clearing a field / setting a field value based on another field (e.g. "when Type=Personal clear Company", "when Country=USA set Currency=USD") | `business-rules` | Business rules are SEPARATE artifacts — do NOT implement them as JavaScript handlers or validators. Use `create-page-business-rules` or `create-entity-business-rules`. Clearing and setting field values is done with the page business rule `set-values` action (set an empty value to clear) — NO handler needed. |
		       | restricting / filtering which records a lookup or ComboBox field offers (e.g. "limit a lookup to records whose <field> equals <value>", "show only records created within a relative period", "only <records> that have at least one related <child>", "show the <Field> only for <records> where <condition>") | `business-rules` | Lookup record-set restriction is an ENTITY business rule (`apply-static-filter`), NOT a page edit. Do NOT add `filterConfig` / `staticFilters` / `dataSourceFilters` to a datasource list attribute for this — call `create-entity-business-rules`. The entity rule applies everywhere the lookup is used and is validated; hand-edited page filters are page-scoped and brittle. This holds for ANY constraint mechanism — attribute value, now-relative period (date macro), fixed calendar/clock part such as a time of day (datePart), existence/count of related child records, or gating by another field's value — all are apply-static-filter, never a handler/crt.InitRequest; classify the mechanism, not the wording. A gated constraint puts the gate (X = Y) in the rule's condition group with the apply-static-filter action on the target lookup. |
		       | email as mailto link, phone as tel link, text uppercase/lowercase, boolean inversion, number/currency formatting, any display-only transformation | `page-schema-converters` | Determines whether a converter is the right tool BEFORE you choose a component type. Skipping this causes AI to use crt.EmailInput instead of crt.ToEmailLink, or crt.Label instead of a converter binding. |
		       | business logic, cross-field orchestration, async data loading, side effects | `page-schema-handlers` | Handlers are NOT the same as converters. NOTE: restricting which records a lookup/ComboBox offers is NEVER handler "business logic" — regardless of the constraint mechanism (attribute value, relative period, fixed time-of-day, child existence/count, or gating by another field); it is an entity business rule (apply-static-filter). See the lookup-restriction row above. |
		       | showing a user-facing message/confirmation/info/success/error popup when a button or menu item is clicked (e.g. "just show a short confirmation message", "Approved." / "Saved.") | `page-schema-handlers` | This is a `crt.ShowDialogRequest` dispatched from a handler (message/actions under `dialogConfig.data`), and needs `@creatio-devkit/common` in `SCHEMA_DEPS` + the `sdk` alias in `SCHEMA_ARGS`. NEVER use `alert(...)`, `window.alert(...)`, `confirm(...)`, or `prompt(...)` (raw browser primitives, not the Freedom UI dialog). |
		       | add a button/menu item that runs a business process (`clicked` -> `crt.RunBusinessProcessRequest`) | `run-process-button` | Resolve the process with `get-process-signature` FIRST; every parameter key (in `processParameters` / `parameterMappings` / `recordIdProcessParameterName`) must be the process parameter CODE, not the caption — the platform silently drops values keyed by an unknown code. `processRunType` is required. No custom handler needed. |
		       | required field, max length, format enforcement with error message | `page-schema-validators` | Validators write to viewModelConfigDiff, not viewConfigDiff. |
		       | SDK service calls (SysSettingsService, HttpClientService, etc.) | `page-schema-creatio-devkit-common` | Correct import syntax and async patterns. |
		       | any static/generated filter where path normalization, lookup GUID resolution, date-relative wording, or child-record conditions are involved | `esq-filters-frontend` | Filter generation frequently fails on `...Id` path usage, lookup value shape, relative-date semantics, and missing EXISTS/backward-reference modeling. Read the dedicated serialized-filter guide before writing the payload. |
		       | adding a related/child list (a "detail") to a record page, OR a list/grid that must show only the records belonging to the current/open record (e.g. "add a Contacts detail", "list the Orders for this account", "filter the list by the page record / by page data") | `related-list` | A detail is a composite — its structure is the `get-component-info composite="Expanded list"` recipe and "filter by page data" is declarative master-detail wiring: a child `crt.EntityDataSource`, an `isCollection` attribute, and a `modelConfig.dependencies` entry (`attributePath`/`relationPath`) — NOT an inline `filter`, NOT an init handler, NOT a seeded filter attribute. Read the dedicated guide before writing the body or the list shows all records / none. |
		       | working with a dashboard page (a page inherited from `BaseDashboardTemplate`) — creating one, or adding/arranging/sizing/styling any analytics widget (metric/indicator or chart) on it | `dashboards` | Mandatory read first — the `dashboards` router points you to dashboard-creation (create the page + its optional properties) or dashboard-design (widget layout, sizing, styling), and onward to `indicator-widget` / `chart-widget` + `get-component-info` for a widget's runtime contract. |
		       | body contains `$Resources.Strings.*` or `#ResourceString(...)#`, or you plan to pass the `resources` parameter, OR your change adds/edits ANY user-visible string-like property (label, caption, title, tooltip, placeholder, description, button captions, tab/group titles, validator/dialog messages — examples, not exhaustive) | `page-schema-resources` | Every user-visible string must be a localizable-string binding, not an inline literal. Most resource registrations for DS-bound captions (e.g. `PDS_UsrStatus`) are unnecessary because the platform auto-provides them; guidance specifies which keys must vs must-not be registered, and `$Resources.Strings.*` is rejected in validator params. update-page / sync-pages / validate-page HARD-REJECT an inline literal for label, caption, title, tooltip, or placeholder — the save fails until you bind it and register the key's default-language value. |
		       | body contains `operation:"insert"` in `viewConfigDiff` for a standard field component (crt.Input, crt.NumberInput, crt.Checkbox, crt.ComboBox, crt.PhoneInput, crt.EmailInput, crt.DateTimePicker, crt.WebInput, crt.RichTextEditor, crt.ColorPicker, crt.ImageInput, crt.FileInput, crt.EncryptedInput, crt.Slider) | `page-modification-field-contract` | A field control insert is more than a viewConfigDiff entry — missing the viewModelConfigDiff binding attribute or a resolvable label is silently catastrophic (no data source / blank caption) and now hard-rejected by `update-page` validation. |

		       STOP. Do NOT call get-component-info and pick a component type to solve a display transformation requirement until you have read `page-schema-converters` and confirmed the OOTB decision table does not cover your case. A common mistake is treating a display transformation as a component selection problem.

		       STOP. Touching resources at all? Read `page-schema-resources` first. This covers any body that contains `$Resources.Strings.*` or `#ResourceString(...)#`, any call that passes the `resources` parameter, AND any change that adds or modifies a user-visible string-like property — no exceptions, no "simple cases". This is enforced, not advisory: update-page / sync-pages / validate-page HARD-REJECT a body that sets `label`, `caption`, `title`, `tooltip`, or `placeholder` to an inline literal anywhere in `viewConfigDiff`. When you author a new placeholder/title/caption, also register its default-language value via `resources` (e.g. `placeholder: "$Resources.Strings.EmailField_placeholder"` + `resources: '{"EmailField_placeholder": "name@firm.com"}'`).

		       STOP. Want to limit / filter which records a lookup or ComboBox field shows? That is NOT a page edit. Do NOT add `filterConfig`, `staticFilters`, or `dataSourceFilters` to a datasource list attribute (e.g. `PDS_UsrAssignee_*_List`) to restrict the offered records — call `get-guidance` with name `business-rules` and create the restriction with `create-entity-business-rules` (`apply-static-filter`). A common mistake is treating "show only contacts who…" / "limit the Assignee field to…" as a page filterConfig change instead of an entity business rule.
		       STOP. "show the <LookupField> only for <records> where <condition>" (e.g. "show the Assignee field only for contacts where Age = 30") is NOT a field-visibility request. It means RESTRICT which records the lookup offers — use `create-entity-business-rules` (`apply-static-filter`). Do NOT set the field `visible:false`, do NOT use hide-element/show-element, and do NOT add a page attribute or filterConfig. hide-element/show-element are only for the field itself appearing/disappearing, never for which records a lookup lists.
		       STOP. Finding an EXISTING `filterConfig` / `staticFilters` already on the page does NOT mean a lookup-restriction request is already satisfied. That stray page filter is the wrong artifact (often left by a previous incorrect attempt). Do not short-circuit to "already done": create the entity business rule with `create-entity-business-rules` (`apply-static-filter`), and remove the stray page `filterConfig` from the datasource list attribute so it does not mask or duplicate the rule.

		       STOP — COMPONENT-TYPE VERIFICATION IS MANDATORY before you put ANY component `type` into a `viewConfigDiff` `insert`. NEVER author a `crt.*` type from memory, by analogy to another UI framework, or because the name "sounds right". `update-page`/`sync-pages` do NOT validate that a component type exists — they accept an unknown type and report `success: true`, but Freedom UI cannot resolve it and renders the unknown-component fallback: a grey placeholder box that literally prints the type string with a loading spinner (no control, no data, no buttons). A reported success is therefore NOT proof the component works.
		       For EVERY component type you intend to insert:
		       1. Call `get-component-info` with `component-type` set to that exact type and `environment-name` set to the same environment you are editing the page on. Confirm the response is `mode: "detail"` with `success: true`. A `success: false` not-found response (it returns the closest known types as suggestions) means the type does NOT exist on that environment — do NOT use it.
		       2. If you cannot find an OOTB component that actually satisfies the requirement — the catalog has no match, or the closest match does not do what the user asked — do NOT silently invent a type, do NOT substitute a similarly-named one, and do NOT create a custom component on your own initiative to "make it work". STOP and ASK THE USER how to proceed, presenting the two options explicitly: (a) use one of the existing OOTB components you found (list the closest candidates from `get-component-info`), or (b) build a new custom component. Wait for the user's choice before writing the body.

		       STOP. Adding a related/child list (a "detail"), or making a list show only the records that belong to the current/open record ("filter by page data"), is NOT a single-component insert and NOT an inline `filter` on the list attribute. It is a master-detail composite — fetch its structure with `get-component-info composite="Expanded list"` plus a child `crt.EntityDataSource`, an `isCollection` attribute, and a declarative `modelConfig.dependencies` entry (`attributePath` = child foreign-key column, `relationPath` = master id path such as `PDS.Id`). Read `get-guidance` with name `related-list` before writing the body. Do NOT scope the list with a `crt.HandleViewModelInitRequest` handler, a seeded empty-Guid filter, or a `filterAttributes` entry — the platform applies the dependency filter for you and waits for the master to load.

		       Canonical flow: `list-pages` -> `get-page` -> `get-component-info` for EVERY type you insert (verify it exists — see the COMPONENT-TYPE VERIFICATION step above) -> edit raw.body -> `update-page`/`sync-pages` (optionally `verify:true`). Do NOT resend the full raw.body. Full flow + response shapes: `page-modification-overview`.
		       """
	};

	/// <summary>
	/// Returns the canonical guidance article for Freedom UI page modification.
	/// </summary>
	[McpServerResource(UriTemplate = ResourceUri, Name = "page-modification-guidance")]
	[Description("Returns the entry guidance for Freedom UI page modification: the mandatory pre-edit GATE checklist and canonical flow, routing the detailed mechanics to the page-modification-overview / -field-contract / -containers / -components sub-guides.")]
	public ResourceContents GetGuide() => Guide;
}
