using System.ComponentModel;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace Clio.Command.McpServer.Resources;

/// <summary>
/// Provides canonical AI-facing guidance for designing Creatio business processes (BPMN) through clio MCP:
/// the element catalog, the connection rules (R1–R17), and the validate-then-drive build recipe.
/// </summary>
[McpServerResourceType]
public sealed class ProcessModelingGuidanceResource {
	private const string DocsScheme = "docs";
	private const string ResourcePath = "mcp/guides/process-modeling";
	private const string ResourceUri = DocsScheme + "://" + ResourcePath;

	/// <summary>
	/// Returns the canonical guidance article for AI-driven Creatio business process modeling.
	/// </summary>
	[McpServerResource(UriTemplate = ResourceUri, Name = "process-modeling-guidance")]
	[Description("Returns canonical MCP guidance for designing Creatio business processes: BPMN element catalog, connection rules R1-R17, and the validate-then-drive build recipe.")]
	public ResourceContents GetGuide() => Guide;

	internal static readonly TextResourceContents Guide = new() {
		Uri = ResourceUri,
		MimeType = "text/plain",
		Text = """
			clio MCP process-modeling guide — design Creatio business processes (BPMN)

			== Determinism contract (read first) ==
			- clio makes no LLM call. You own the intent->BPMN translation: you decide which elements the
			  process needs, what their parameters are, and how they connect. clio only runs deterministic steps.
			- Metadata is owned by the designer. Never hand-author process metadata, filters, or column
			  mappings — express intent; the visual Process Designer (which clio drives via the process-* tools)
			  serializes it. Producing valid process metadata by hand is error-prone and is not your job.
			- Before driving the designer, call `validate-process-graph` with your planned graph (nodes as
			  data-id strings + flows). Resolve every error-severity finding before building.
			- The live designer is the FINAL authority. After each connection clio checks the flow for the
			  `.djs-validate-outline` marker; if present, the connection is invalid and is reverted. Treat the
			  static validator as a fast pre-check, not the source of truth — the designer's own rules win.

			== Supported slice (what clio can DRIVE today) ==
			- Start events: Simple/Signal/Timer start.
			- Activity: Read data (data-id `readDataUserTask`).
			- Everything else in the catalog below is described for context, not yet drivable by clio. Use it to
			  reason about a solution and to read/explain existing processes (`describe-process`), but do not
			  expect a `process-add-element` driver for those types in this increment.

			== Build recipe (intent -> running process) ==
			1. Translate the request into a graph: one start event, the activities, the sequence/conditional
			   flows, and an end event.
			2. `validate-process-graph(graph)` -> fix all errors.
			3. For each element, `process-add-element(...)`: clio opens the authenticated designer (CDP), appends
			   the element from the source element's context pad (`add.serviceTask` defaults to `readDataUserTask`),
			   morphs it to the target data-id if needed (`[data-action=setup]` -> group -> data-id), fills the
			   right-panel setup card, connects (`connect`), checks `.djs-validate-outline` is absent, and saves.
			4. Verify: `describe-process` / `generate-process-model` / `execute-esq` (VwProcessLib by caption).

			== Element catalog (data-id -> label -> purpose) ==
			System actions (palette group "System actions"):
			- `readDataUserTask`  Read data    — read first record / aggregate / count / collection of an object.
			    Setup fields: DataReadMode, EntitySchemaSelect (object), filters, SortByColumn_N, ColumnSelectMode.
			- `addDataUserTask`   Add data     — create record(s) in background; one-record mode returns only the Id.
			- `changeDataUserTask` Modify data — bulk-update matched records (same values to all).
			- `deleteDataUserTask` Delete data — delete matched records.
			- `formulaTask`       Formula      — compute a value (math/string/date/bool) into an output param.
			- `scriptTask`        Script task  — custom C# (ends with `return true;`; needs publication).
			- `webService`        Call web service — call a registered service; outputs Success + Http status code.
			- `callActivity`      Sub-process  — run another process (must start with a Simple start); multi-instance over a collection.
			- `userTask`/`*UserTask` — user/system tasks (Perform task, Open edit page, Send email, Approval, etc.).
			User actions: `activityUserTask` Perform task, `userQuestionUserTask` User dialog,
			  `openEditPageUserTask` Open edit page, `autoGeneratedPageUserTask` Auto-generated page,
			  `preconfiguredPageUserTask` Pre-configured page, `emailTemplateUserTask` Send email, `approvalUserTask` Approval.
			Events: `startEvent` Simple start, `startEventSignal` Signal start (record add/modify/delete or custom
			  signal), `startEventTimer` Start timer (schedule/CRON), `startEventMessage` Start message, intermediate
			  catch/throw (`intermediateCatchEvent*`/`intermediateThrowEvent*`), `endEvent` End/Terminate.
			Gateways: `exclusiveGateway` (OR), `parallelGateway` (AND), `inclusiveGateway` (OR), `eventBasedGateway`.
			Flows: sequence (default `connect`), conditional (setup -> conditionalConnection), default (setup -> defaultConnection).

			== Parameters / mapping / formulas ==
			- Parameters: process-level (Parameters tab) vs element-level. Types: Text, Integer/Decimal, Boolean,
			  Lookup, Date/Time, Currency, Collection, Id. Direction: Input (set before) / Output (set during) /
			  bi-directional (sub-process). Value sources: constant, system setting/variable, formula, or another parameter.
			- Mapping: bind a later element's input to an earlier element's output via the value-picker
			  (Process parameter -> source element -> source parameter). Reference syntax `[#ElementName.PropertyPath#]`,
			  e.g. `[#Read data.First item.Id#]`, `[#Read products.First element of the resulting collection.Name#]`.
			  Add data returns only `Id` -> chain a Read data to read other fields.
			- Formulas: C#-like, strictly typed (convert with `.ToString()` etc.). Examples: `"text " + [#param#]`,
			  `[#System variable.Current date and time#].AddDays(3)`, `([#A#] - [#B#]).TotalHours`.

			== Connection rules R1–R17 (pre-checked by validate-process-graph) ==
			R1  Start event: no incoming flow; exactly one outgoing.
			R2  End event: no outgoing flow; one or more incoming.
			R3  Exactly one top-level start event; every path reaches an end event.
			R4  Terminate end kills the whole instance; Simple end ends only its path.
			R5  Start triggers: Simple=user/run; Signal(object)=record add/modify/delete; custom signal=broadcast; message=directed; timer=schedule/CRON.
			R6  Diverging gateway: 1 in, >=2 out. Converging gateway: >=2 in, 1 out.
			R7  Exclusive(OR) diverge: conditional flows + exactly one default; one path taken. Converge: first arrival, no sync.
			R8  Parallel(AND) diverge: all out fire, plain sequence flows only. Converge: waits for all incoming.
			R9  Inclusive(OR) diverge: conditional flows + required default; >=1 path. Converge: syncs active branches.
			R10 Event-based gateway: each outgoing sequence flow leads directly to an intermediate catch event; first event wins.
			R11 Parallel and event-based gateways must not carry conditional/default flows.
			R12 Sequence flow: target runs after source. Multiple outgoing sequence flows = implicit parallel split.
			R13 Conditional flow originates only from a gateway or an activity.
			R14 Default flow is legal only if >=1 conditional flow leaves the same element; diverging Exclusive/Inclusive require a default.
			R15 No orphan/unreachable nodes; every flow needs a valid source and target.
			R16 Sub-process (callActivity) target must begin with a Simple start; collection mapping => multi-instance.
			R17 (advisory) Add data one-record mode outputs only Id; chain a Read data for other fields.

			Quick can/can't (source -> target via sequence flow): start->{activity,gateway,intermediate,end} ok,
			never ->start (R1); end is a sink, never a source (R2); event-based gateway out must hit a catch event (R10).
			"""
	};
}
