apiVersion: v1
kind: Service
metadata:
  name: clio-email-listener
  namespace: clio-infrastructure
  annotations:
    a8r.io/description: "This service exposes email-listener outside the cluster, used by creatio running outside the cluster"
  labels:
    app: clio-email-listener
spec:
    selector:
      app: clio-email-listener
    type: LoadBalancer
    ports:
    - port: 1090
      targetPort: 8080
